local flag_array = {
	{byte=0x00, bit=0, name="Japes: First Gate Opened"},
	{byte=0x00, bit=1, name="Japes: Mad Maze Maul GB", type="Bunch"},
	{byte=0x00, bit=2, name="Japes: Splish Splash Salvage GB", type="GB"},
	{byte=0x00, bit=3, name="Japes: Baboon Blast GB", type="GB"},
	{byte=0x00, bit=4, name="Japes: DK GB: In front of Diddy's cage", type="GB", map=7},
	{byte=0x00, bit=5, name="Japes: Free Diddy GB", type="GB"},
	{byte=0x00, bit=6, name="Kong Unlocked: Diddy", type="Kong", map=7},
	{byte=0x00, bit=7, name="Japes: Shellhive Gate Opened"},

	{byte=0x01, bit=0, name="Japes: Stump GB", type="GB"},
	{byte=0x01, bit=1, name="Japes: Shellhive GB", type="GB"},
	{byte=0x01, bit=2, name="Japes: Painting Room GB", type="GB"},
	{byte=0x01, bit=3, name="Japes: Speedy Swing Sortie GB", type="GB"},
	{byte=0x01, bit=4, name="Japes: Underground GB", type="GB"},
	{byte=0x01, bit=5, name="Japes: Diddy Hut Broken"},
	{byte=0x01, bit=6, name="Japes: Lanky Hut Broken"},
	{byte=0x01, bit=7, name="Japes: DK Hut Broken"},

	{byte=0x02, bit=0, name="Japes: Tiny Hut Broken"},
	{byte=0x02, bit=2, name="Japes: Diddy Caged GB", type="GB"},
	{byte=0x02, bit=3, name="Japes: Lanky Caged GB", type="GB"},
	{byte=0x02, bit=4, name="Japes: DK Caged GB", type="GB"},
	{byte=0x02, bit=5, name="Japes: Tiny Caged GB", type="GB"},
	{byte=0x02, bit=6, name="Japes: Chunky Caged GB", type="GB"},
	{byte=0x02, bit=7, name="Japes: Mountain GB", type="GB"},

	{byte=0x03, bit=0, name="Japes: Diddy Minecart GB", type="GB"},
	{byte=0x03, bit=1, name="Japes: Rock GB", type="GB"},
	{byte=0x03, bit=2, name="Key 1", type="Key", map=8},
	{byte=0x03, bit=4, name="Japes: Minecart Mayhem GB", type="GB"},
	{byte=0x03, bit=5, name="Chunky CB: Japes: Rambi Area", type="Bunch"},
	{byte=0x03, bit=6, name="Japes: Painting Room Opened"},
	{byte=0x03, bit=7, name="Japes: Cave GB", type="GB"},

	{byte=0x04, bit=0, name="Japes: Warp 1 (DK Portal)", type="Warp"},
	{byte=0x04, bit=1, name="Japes: Warp 1 (Main)", type="Warp"},
	{byte=0x04, bit=2, name="Japes: Warp 2 (Mountain)", type="Warp"},
	{byte=0x04, bit=3, name="Japes: Warp 2 (Main)", type="Warp"},
	{byte=0x04, bit=4, name="Japes: Warp 3 (Right)", type="Warp"},
	{byte=0x04, bit=5, name="Japes: Warp 3 (Left)", type="Warp"},
	{byte=0x04, bit=6, name="Japes: Warp 5 (Hive)", type="Warp"},

	{byte=0x05, bit=0, name="Japes: Warp 4 (Front)", type="Warp"},
	{byte=0x05, bit=1, name="Japes: Warp 4 (Cranky)", type="Warp"},
	{byte=0x05, bit=2, name="Japes: Find Diddy", type="Cutscene"},
	{byte=0x05, bit=3, name="Japes: Rambi Door Broken"},
	{byte=0x05, bit=4, name="Japes: Mountain Bridge Cutscene", type="Cutscene"},
	{byte=0x05, bit=5, name="Japes: Rambi Coconut Switch"},
	{byte=0x05, bit=6, name="Japes: T&S Cleared", type="T&S", map=7},
	{byte=0x05, bit=7, name="Japes: Cave Gate Opened"},

	{byte=0x08, bit=3, name="Kong Unlocked: Tiny", type="Kong", map=16},
	{byte=0x08, bit=4, name="Aztec: Diddy GB: Tiny's Cage", type="GB", map=16},
	{byte=0x08, bit=7, name="Kong Unlocked: Lanky", type="Kong", map=20},

	{byte=0x09, bit=3, name="Key 2", type="Key", map=197},
	{byte=0x09, bit=6, name="Aztec: DK GB: Free Lanky", type="GB", map=20},

	{byte=0x0A, bit=0, name="Aztec: Warp 1 (DK Portal)", type="Warp"},
	{byte=0x0A, bit=1, name="Aztec: Warp 1 (Oasis)", type="Warp"},
	{byte=0x0A, bit=2, name="Aztec: Warp 2 (Oasis)", type="Warp"},
	{byte=0x0A, bit=3, name="Aztec: Warp 2 (Totem)", type="Warp"},
	{byte=0x0A, bit=4, name="Aztec: Warp 3 (Cranky)", type="Warp"},
	{byte=0x0A, bit=5, name="Aztec: Warp 3 (Totem)", type="Warp"},
	{byte=0x0A, bit=6, name="Aztec: Warp 4 (Funky)", type="Warp"},
	{byte=0x0A, bit=7, name="Aztec: Warp 4 (Totem)", type="Warp"},

	{byte=0x0B, bit=0, name="Aztec: W5 (Exterior)", type="Warp"},
	{byte=0x0B, bit=1, name="Aztec: W1 (Llama temple, high)", type="Warp", map=20},
	{byte=0x0B, bit=2, name="Aztec: W1 (Llama temple, low)", type="Warp", map=20},
	{byte=0x0B, bit=3, name="Aztec: W2 (Llama temple, far)", type="Warp", map=20},
	{byte=0x0B, bit=4, name="Aztec: W2 (Llama temple, low)", type="Warp", map=20},
	{byte=0x0B, bit=5, name="Aztec: Find Llama Cutscene", type="Cutscene"},
	{byte=0x0B, bit=6, name="Aztec: Lanky's help me cutscene", type="Cutscene", map=20},
	{byte=0x0B, bit=7, name="Aztec: Tiny's help me cutscene", type="Cutscene", map=16},

	{byte=0x0E, bit=6, name="Kong Unlocked: Chunky", type="Kong", map=26},
	{byte=0x0E, bit=7, name="Factory: Lanky GB: Free Chunky", type="GB", map=26},

	{byte=0x10, bit=5, name="Nintendo Coin", type="Coin"},

	{byte=0x11, bit=3, name="Key 3", type="Key", map=154},
	{byte=0x11, bit=5, name="Factory: Chunky's help me cutscene", type="Cutscene", map=26},
	{byte=0x11, bit=6, name="Factory: Warp 1 (Lobby)", type="Warp"},
	{byte=0x11, bit=7, name="Factory: Warp 1 (Storage Room)", type="Warp"},

	{byte=0x12, bit=0, name="Factory: Warp 2 (Lobby)", type="Warp"},
	{byte=0x12, bit=1, name="Factory: Warp 2 (R&D)", type="Warp"},
	{byte=0x12, bit=2, name="Factory: Warp 3 (Lobby)", type="Warp"},
	{byte=0x12, bit=3, name="Factory: Warp 3 (Snide)", type="Warp"},
	{byte=0x12, bit=4, name="Factory: Warp 4 (Upper)", type="Warp"},
	{byte=0x12, bit=5, name="Factory: Warp 4 (Lower)", type="Warp"},	
	{byte=0x12, bit=6, name="Factory: Warp 5 (Funky)", type="Warp"},
	{byte=0x12, bit=7, name="Factory: Warp 5 (Arcade)", type="Warp"},

	{byte=0x15, bit=1, name="Key 4", type="Key", map=111},
	{byte=0x15, bit=2, name="Galleon: Warp 5 (Watery Bit)", type="Warp"},
	{byte=0x15, bit=3, name="Galleon: Warp 5 (Lighthouse)", type="Warp"},
	{byte=0x15, bit=4, name="Galleon: Warp 2 (Watery Bit)", type="Warp"},
	{byte=0x15, bit=5, name="Galleon: Warp 2 (Main)", type="Warp"},
	{byte=0x15, bit=6, name="Galleon: Warp 3 (Snide)", type="Warp"},
	{byte=0x15, bit=7, name="Galleon: Warp 3 (Main)", type="Warp"},

	{byte=0x16, bit=0, name="Galleon: Warp 4 (Watery Bit)", type="Warp"},
	{byte=0x16, bit=2, name="Galleon: Warp 1 (Lighthouse)", type="Warp"},
	{byte=0x16, bit=3, name="Galleon: Warp 1 (Main)", type="Warp"},

	{byte=0x19, bit=4, name="Galleon: T&S Cleared", type="T&S", map=30},

	{byte=0x1D, bit=5, name="Key 5", type="Key", map={83, 197}},
	{byte=0x1D, bit=6, name="Fungi: Warp 1 (Mill)", type="Warp"},
	{byte=0x1D, bit=7, name="Fungi: Warp 1 (Clock)", type="Warp"},

	{byte=0x1E, bit=0, name="Fungi: Warp 2 (Clock)", type="Warp"},
	{byte=0x1E, bit=1, name="Fungi: Warp 2 (Apple)", type="Warp"},
	{byte=0x1E, bit=2, name="Fungi: Warp 3 (Clock)", type="Warp"},
	{byte=0x1E, bit=3, name="Fungi: Warp 3 (Mushroom)", type="Warp"},
	{byte=0x1E, bit=4, name="Fungi: Warp 4 (Clock)", type="Warp"},
	{byte=0x1E, bit=5, name="Fungi: Warp 4 (Tree)", type="Warp"},
	{byte=0x1E, bit=6, name="Fungi: Warp 5 (Lower)", type="Warp"},
	{byte=0x1E, bit=7, name="Fungi: Warp 5 (Upper)", type="Warp"},

	{byte=0x20, bit=2, name="Fungi: Pan Cutscene", type="Cutscene"},

	{byte=0x23, bit=4, name="Caves: Warp 1 (5DI)", type="Warp"},
	{byte=0x23, bit=5, name="Caves: Warp 1 (Base)", type="Warp"},
	{byte=0x23, bit=6, name="Caves: Warp 2 (Base)", type="Warp"},
	{byte=0x23, bit=7, name="Caves: Warp 2 (Waterfall)", type="Warp"},

	{byte=0x24, bit=0, name="Caves: Warp 4 (Diddy Kasplat)", type="Warp"},
	{byte=0x24, bit=1, name="Caves: Warp 4 (Pillar)", type="Warp"},
	{byte=0x24, bit=2, name="Caves: Warp 5 (5DC)", type="Warp"},
	{byte=0x24, bit=3, name="Caves: Warp 5 (Lanky Kasplat)", type="Warp"},
	{byte=0x24, bit=4, name="Caves: Warp 3 (5DI)", type="Warp"},
	{byte=0x24, bit=5, name="Key 6", type="Key", map=196},

	{byte=0x25, bit=4, name="Giant Kosha Cutscene Cleared", type="Cutscene"},
	{byte=0x25, bit=5, name="Giant Kosha Dead"},
	{byte=0x25, bit=6, name="Isles: Rareware GB", type="GB"},
	{byte=0x25, bit=7, name="Caves: T&S Cleared", type="T&S", map=72},

	{byte=0x27, bit=6, name="Key 7", type="Key", map=199},

	{byte=0x29, bit=0, name="Castle: Warp 1 (Base)", type="Warp"},
	{byte=0x29, bit=1, name="Castle: Warp 1 (Far)", type="Warp"},
	{byte=0x29, bit=2, name="Castle: Warp 2 (Base)", type="Warp"},
	{byte=0x29, bit=3, name="Castle: Warp 2 (Upper)", type="Warp"},
	{byte=0x29, bit=4, name="Castle: Warp 3 (Base)", type="Warp"},
	{byte=0x29, bit=4, name="Castle: Warp 3 (Upper)", type="Warp"},
	{byte=0x29, bit=6, name="Castle: Warp 4 (Base)", type="Warp"},
	{byte=0x29, bit=7, name="Castle: Warp 4 (Upper)", type="Warp"},

	{byte=0x2A, bit=0, name="Castle: Warp 5 (Base)", type="Warp"},
	{byte=0x2A, bit=1, name="Castle: Warp 5 (Upper)", type="Warp"},
	{byte=0x2A, bit=2, name="Castle: Warp 1 (Crypt - Base)", type="Warp"},
	{byte=0x2A, bit=3, name="Castle: Warp 1 (Crypt - Far)", type="Warp"},
	{byte=0x2A, bit=4, name="Castle: Warp 2 (Crypt - Base)", type="Warp"},
	{byte=0x2A, bit=5, name="Castle: Warp 2 (Crypt - Far)", type="Warp"},
	{byte=0x2A, bit=6, name="Castle: Warp 3 (Crypt - Base)", type="Warp"},
	{byte=0x2A, bit=7, name="Castle: Warp 3 (Crypt - Far)", type="Warp"},

	{byte=0x2C, bit=1, name="Castle: T&S Cleared", type="T&S", map=87},
	{byte=0x2C, bit=4, name="Warp pad FTT", type="FTT"},
	{byte=0x2C, bit=5, name="Japes: ButWhereWasCranky Baboon Blast Cutscene", type="Cutscene"},

	{byte=0x2D, bit=5, name="Rainbow Coin FTT", type="FTT"},
	{byte=0x2D, bit=6, name="First time Rambi Text(?)", type="FTT"},

	{byte=0x2E, bit=4, name="First Orange Collected"},

	{byte=0x2F, bit=2, name="Camera/Shockwave", map=189},
	{byte=0x2F, bit=3, name="Intro Story Cleared", type="Cutscene"},
	{byte=0x2F, bit=4, name="Rareware Coin", type="Coin", map=5},
	{byte=0x2F, bit=5, name="Key 8", type="Key", map=17},
	{byte=0x2F, bit=6, name="Isles: First GB", type="GB"},

	{byte=0x30, bit=0, name="Training Grounds: Spawn Training Barrels Cutscene", type="Cutscene"},
	{byte=0x30, bit=2, name="Kong Unlocked: DK", type="Kong"},
	{byte=0x30, bit=3, name="Training Grounds: Dive Barrel Completed", type="Training Barrels"},
	{byte=0x30, bit=4, name="Training Grounds: Vine Barrel Completed", type="Training Barrels"},
	{byte=0x30, bit=5, name="Training Grounds: Orange Barrel Completed", type="Training Barrels"},
	{byte=0x30, bit=6, name="Training Grounds: Barrel Barrel Completed", type="Training Barrels"},
	{byte=0x30, bit=7, name="Isles: Escape CS", type="Cutscene"},

	{byte=0x31, bit=0, name="Training Grounds: Training Barrels Done Cutscene", type="Cutscene"},
	{byte=0x31, bit=4, name="First Banana Collected"},
	{byte=0x31, bit=5, name="First Coin Collected"},
	{byte=0x31, bit=7, name="Isles: Lanky Instrument GB", type="GB"},

	{byte=0x32, bit=2, name="Isles: Galleon Lobby Grate Opened"},
	{byte=0x32, bit=3, name="Isles: Big Bug Bash GB", type="GB"},
	{byte=0x32, bit=4, name="Isles: Galleon Lobby GB", type="GB"},
	{byte=0x32, bit=5, name="Isles: DK Instrument GB", type="GB"},
	{byte=0x32, bit=7, name="Isles: Kremling Kosh GB", type="GB"},

	{byte=0x33, bit=3, name="Isles: Diddy Instrument GB", type="GB"},
	{byte=0x33, bit=4, name="Isles: Caves Lobby GB", type="GB"},

	{byte=0x34, bit=0, name="Isles: Castle Lobby GB", type="GB"},
	{byte=0x34, bit=1, name="Isles: Batty Barrel Bandit GB", type="GB"},
	{byte=0x34, bit=2, name="Isles: Warp 1 (Helm Lobby - Near)", type="Warp"},
	{byte=0x34, bit=3, name="Isles: Warp 1 (Helm Lobby - Far)", type="Warp"},
	{byte=0x34, bit=4, name="Isles: DK Caged GB", type="GB"},
	{byte=0x34, bit=5, name="Isles: Tiny Caged GB", type="GB"},
	{byte=0x34, bit=6, name="Isles: Lanky Caged GB", type="GB"},
	{byte=0x34, bit=7, name="Isles: Chunky Caged GB", type="GB"},

	{byte=0x35, bit=0, name="Isles: Diddy Caged GB", type="GB"},
	{byte=0x35, bit=1, name="Isles: Chunky Instrument GB", type="GB"},
	{byte=0x35, bit=2, name="Isles: Tiny Instrument GB", type="GB"},
	{byte=0x35, bit=4, name="Hunky Chunky Barrel Spawned"},
	{byte=0x35, bit=5, name="Isles: Summit GB", type="GB"},
	{byte=0x35, bit=6, name="Isles: K-Lumsy Cage GB", type="GB"},

	{byte=0x36, bit=0, name="Isles: Pound the X GB", type="GB"},
	{byte=0x36, bit=1, name="Bananaporter First Time Text", type="FTT"},
	{byte=0x36, bit=2, name="Isles: W1 (Ring)", type="Warp", map=34},
	{byte=0x36, bit=3, name="Isles: W1 (Far)", type="Warp", map=34},
	{byte=0x36, bit=4, name="Isles: W2 (Ring)", type="Warp", map=34},
	{byte=0x36, bit=5, name="Isles: W2 (High)", type="Warp", map=34},
	{byte=0x36, bit=6, name="Isles: W3 (Ring)", type="Warp", map=34},
	{byte=0x36, bit=7, name="Isles: W3 (Far)", type="Warp", map=34},

	{byte=0x37, bit=0, name="Isles: W4 (Ring)", type="Warp", map=34},
	{byte=0x37, bit=1, name="Isles: W4 (High)", type="Warp", map=34},
	{byte=0x37, bit=2, name="Isles: W5 (Far)", type="Warp", map=34},
	{byte=0x37, bit=3, name="Isles: W5 (Ring)", type="Warp", map=34},
	{byte=0x37, bit=4, name="Isles: Japes Rock Blasted", type="Cutscene"},
	{byte=0x37, bit=5, name="Key 1 Turned", type="Key", map={34,97}},
	{byte=0x37, bit=6, name="Key 2 Turned", type="Key", map={34,97}},
	{byte=0x37, bit=7, name="Key 3 Turned", type="Key", map={34,97}},

	{byte=0x38, bit=0, name="Key 4 Turned", type="Key", map={34,97}},
	{byte=0x38, bit=1, name="Key 5 Turned", type="Key", map={34,97}},
	{byte=0x38, bit=2, name="Key 6 Turned", type="Key", map={34,97}},
	{byte=0x38, bit=3, name="Key 7 Turned", type="Key", map={34,97}},
	{byte=0x38, bit=4, name="Key 8 Turned", type="Key", map={34,97}},

	{byte=0x3A, bit=6, name="Japes: DK Blueprint", type="Blueprint", map=7},
	{byte=0x3A, bit=7, name="Japes: Diddy Blueprint", type="Blueprint", map=7},

	{byte=0x3B, bit=0, name="Japes: Lanky Blueprint", type="Blueprint", map=7},
	{byte=0x3B, bit=1, name="Japes: Tiny Blueprint", type="Blueprint", map=7},
	{byte=0x3B, bit=2, name="Japes: Chunky Blueprint", type="Blueprint", map=33},
	{byte=0x3B, bit=3, name="Aztec: DK Blueprint", type="Blueprint", map=38},
	{byte=0x3B, bit=4, name="Aztec: Diddy Blueprint", type="Blueprint", map=38},
	{byte=0x3B, bit=5, name="Aztec: Lanky Blueprint", type="Blueprint", map=20},
	{byte=0x3B, bit=6, name="Aztec: Tiny Blueprint", type="Blueprint", map=38},
	{byte=0x3B, bit=7, name="Aztec: Chunky Blueprint", type="Blueprint", map=24},

	{byte=0x3C, bit=0, name="Factory: DK Blueprint", type="Blueprint", map=26},
	{byte=0x3C, bit=1, name="Factory: Diddy Blueprint", type="Blueprint", map=26},
	{byte=0x3C, bit=2, name="Factory: Lanky Blueprint", type="Blueprint", map=26},
	{byte=0x3C, bit=3, name="Factory: Tiny Blueprint", type="Blueprint", map=26},
	{byte=0x3C, bit=4, name="Factory: Chunky Blueprint", type="Blueprint", map=26},
	{byte=0x3C, bit=5, name="Galleon: DK Blueprint", type="Blueprint", map=30},
	{byte=0x3C, bit=6, name="Galleon: Diddy Blueprint", type="Blueprint", map=30},
	{byte=0x3C, bit=7, name="Galleon: Lanky Blueprint", type="Blueprint", map=30},

	{byte=0x3D, bit=0, name="Galleon: Tiny Blueprint", type="Blueprint", map=30},
	{byte=0x3D, bit=1, name="Galleon: Chunky Blueprint", type="Blueprint", map=30},
	{byte=0x3D, bit=2, name="Fungi: DK Blueprint", type="Blueprint", map=48},
	{byte=0x3D, bit=3, name="Fungi: Diddy Blueprint", type="Blueprint", map=64},
	{byte=0x3D, bit=4, name="Fungi: Lanky Blueprint", type="Blueprint", map=48},
	{byte=0x3D, bit=5, name="Fungi: Tiny Blueprint", type="Blueprint", map=48},
	{byte=0x3D, bit=6, name="Fungi: Chunky Blueprint", type="Blueprint", map=48},
	{byte=0x3D, bit=7, name="Caves: DK Blueprint", type="Blueprint", map=72},

	{byte=0x3E, bit=0, name="Caves: Diddy Blueprint", type="Blueprint", map=72},
	{byte=0x3E, bit=1, name="Caves: Lanky Blueprint", type="Blueprint", map=72},
	{byte=0x3E, bit=2, name="Caves: Tiny Blueprint", type="Blueprint", map=72},
	{byte=0x3E, bit=3, name="Caves: Chunky Blueprint", type="Blueprint", map=72},
	{byte=0x3E, bit=4, name="Castle: DK Blueprint", type="Blueprint", map=164},
	{byte=0x3E, bit=5, name="Castle: Diddy Blueprint", type="Blueprint", map=183},
	{byte=0x3E, bit=6, name="Castle: Lanky Blueprint", type="Blueprint", map=87},
	{byte=0x3E, bit=7, name="Castle: Tiny Blueprint", type="Blueprint", map=87},

	{byte=0x3F, bit=0, name="Castle: Chunky Blueprint", type="Blueprint", map=151},
	{byte=0x3F, bit=1, name="Isles: DK Blueprint", type="Blueprint", map=170},
	{byte=0x3F, bit=2, name="Isles: Diddy Blueprint", type="Blueprint", map=193},
	{byte=0x3F, bit=3, name="Isles: Lanky Blueprint", type="Blueprint", map=194},
	{byte=0x3F, bit=4, name="Isles: Tiny Blueprint", type="Blueprint", map=175},
	{byte=0x3F, bit=5, name="Isles: Chunky Blueprint", type="Blueprint", map=174},
	{byte=0x3F, bit=6, name="Snide's: DK BP Turned (Japes)", type="GB", map=15},
	{byte=0x3F, bit=7, name="Snide's: Diddy BP Turned (Japes)", type="GB", map=15},

	{byte=0x40, bit=0, name="Snide's: Lanky BP Turned (Japes)", type="GB", map=15},
	{byte=0x40, bit=1, name="Snide's: Tiny BP Turned (Japes)", type="GB", map=15},
	{byte=0x40, bit=2, name="Snide's: Chunky BP Turned (Japes)", type="GB", map=15},
	{byte=0x40, bit=3, name="Snide's: DK BP Turned (Aztec)", type="GB", map=15},
	{byte=0x40, bit=4, name="Snide's: Diddy BP Turned (Aztec)", type="GB", map=15},
	{byte=0x40, bit=5, name="Snide's: Lanky BP Turned (Aztec)", type="GB", map=15},
	{byte=0x40, bit=6, name="Snide's: Tiny BP Turned (Aztec)", type="GB", map=15},
	{byte=0x40, bit=7, name="Snide's: Chunky BP Turned (Aztec)", type="GB", map=15},

	{byte=0x41, bit=0, name="Snide's: DK BP Turned (Factory)", type="GB", map=15},
	{byte=0x41, bit=1, name="Snide's: Diddy BP Turned (Factory)", type="GB", map=15},
	{byte=0x41, bit=2, name="Snide's: Lanky BP Turned (Factory)", type="GB", map=15},
	{byte=0x41, bit=3, name="Snide's: Tiny BP Turned (Factory)", type="GB", map=15},
	{byte=0x41, bit=4, name="Snide's: Chunky BP Turned (Factory)", type="GB", map=15},
	{byte=0x41, bit=5, name="Snide's: DK BP Turned (Galleon)", type="GB", map=15},
	{byte=0x41, bit=6, name="Snide's: Diddy BP Turned (Galleon)", type="GB", map=15},
	{byte=0x41, bit=7, name="Snide's: Lanky BP Turned (Galleon)", type="GB", map=15},

	{byte=0x42, bit=0, name="Snide's: Tiny BP Turned (Galleon)", type="GB", map=15},
	{byte=0x42, bit=1, name="Snide's: Chunky BP Turned (Galleon)", type="GB", map=15},
	{byte=0x42, bit=2, name="Snide's: DK BP Turned (Fungi)", type="GB", map=15},
	{byte=0x42, bit=3, name="Snide's: Diddy BP Turned (Fungi)", type="GB", map=15},
	{byte=0x42, bit=4, name="Snide's: Lanky BP Turned (Fungi)", type="GB", map=15},
	{byte=0x42, bit=5, name="Snide's: Tiny BP Turned (Fungi)", type="GB", map=15},
	{byte=0x42, bit=6, name="Snide's: Chunky BP Turned (Fungi)", type="GB", map=15},
	{byte=0x42, bit=7, name="Snide's: DK BP Turned (Caves)", type="GB", map=15},

	{byte=0x43, bit=0, name="Snide's: Diddy BP Turned (Caves)", type="GB", map=15},
	{byte=0x43, bit=1, name="Snide's: Lanky BP Turned (Caves)", type="GB", map=15},
	{byte=0x43, bit=2, name="Snide's: Tiny BP Turned (Caves)", type="GB", map=15},
	{byte=0x43, bit=3, name="Snide's: Chunky BP Turned (Caves)", type="GB", map=15},
	{byte=0x43, bit=4, name="Snide's: DK BP Turned (Castle)", type="GB", map=15},
	{byte=0x43, bit=5, name="Snide's: Diddy BP Turned (Castle)", type="GB", map=15},
	{byte=0x43, bit=6, name="Snide's: Lanky BP Turned (Castle)", type="GB", map=15},
	{byte=0x43, bit=7, name="Snide's: Tiny BP Turned (Castle)", type="GB", map=15},

	{byte=0x44, bit=0, name="Snide's: Chunky BP Turned (Castle)", type="GB", map=15},
	{byte=0x44, bit=1, name="Snide's: DK BP Turned (Isles)", type="GB", map=15},
	{byte=0x44, bit=2, name="Snide's: Diddy BP Turned (Isles)", type="GB", map=15},
	{byte=0x44, bit=3, name="Snide's: Lanky BP Turned (Isles)", type="GB", map=15},
	{byte=0x44, bit=4, name="Snide's: Tiny BP Turned (Isles)", type="GB", map=15},
	{byte=0x44, bit=5, name="Snide's: Chunky BP Turned (Isles)", type="GB", map=15},
	{byte=0x44, bit=6, name="Japes: DK Banana Medal", type="Medal"},
	{byte=0x44, bit=7, name="Japes: Diddy Banana Medal", type="Medal"},

	{byte=0x45, bit=0, name="Japes: Lanky Banana Medal", type="Medal"},
	{byte=0x45, bit=1, name="Japes: Tiny Banana Medal", type="Medal"},
	{byte=0x45, bit=2, name="Japes: Chunky Banana Medal", type="Medal"},
	{byte=0x45, bit=3, name="Aztec: DK Banana Medal", type="Medal"},
	{byte=0x45, bit=4, name="Aztec: Diddy Banana Medal", type="Medal"},
	{byte=0x45, bit=5, name="Aztec: Lanky Banana Medal", type="Medal"},
	{byte=0x45, bit=6, name="Aztec: Tiny Banana Medal", type="Medal"},
	{byte=0x45, bit=7, name="Aztec: Chunky Banana Medal", type="Medal"},

	{byte=0x46, bit=0, name="Factory: DK Banana Medal", type="Medal"},
	{byte=0x46, bit=1, name="Factory: Diddy Banana Medal", type="Medal"},
	{byte=0x46, bit=2, name="Factory: Lanky Banana Medal", type="Medal"},
	{byte=0x46, bit=3, name="Factory: Tiny Banana Medal", type="Medal"},
	{byte=0x46, bit=4, name="Factory: Chunky Banana Medal", type="Medal"},
	{byte=0x46, bit=5, name="Galleon: DK Banana Medal", type="Medal"},
	{byte=0x46, bit=6, name="Galleon: Diddy Banana Medal", type="Medal"},
	{byte=0x46, bit=7, name="Galleon: Lanky Banana Medal", type="Medal"},

	{byte=0x47, bit=0, name="Galleon: Tiny Banana Medal", type="Medal"},
	{byte=0x47, bit=1, name="Galleon: Chunky Banana Medal", type="Medal"},
	{byte=0x47, bit=2, name="Fungi: DK Banana Medal", type="Medal"},
	{byte=0x47, bit=3, name="Fungi: Diddy Banana Medal", type="Medal"},
	{byte=0x47, bit=4, name="Fungi: Lanky Banana Medal", type="Medal"},
	{byte=0x47, bit=5, name="Fungi: Tiny Banana Medal", type="Medal"},
	{byte=0x47, bit=6, name="Fungi: Chunky Banana Medal", type="Medal"},
	{byte=0x47, bit=7, name="Caves: DK Banana Medal", type="Medal"},

	{byte=0x48, bit=0, name="Caves: Diddy Banana Medal", type="Medal"},
	{byte=0x48, bit=1, name="Caves: Lanky Banana Medal", type="Medal"},
	{byte=0x48, bit=2, name="Caves: Tiny Banana Medal", type="Medal"},
	{byte=0x48, bit=3, name="Caves: Chunky Banana Medal", type="Medal"},
	{byte=0x48, bit=4, name="Castle: DK Banana Medal", type="Medal"},
	{byte=0x48, bit=5, name="Castle: Diddy Banana Medal", type="Medal"},
	{byte=0x48, bit=6, name="Castle: Lanky Banana Medal", type="Medal"},
	{byte=0x48, bit=7, name="Castle: Tiny Banana Medal", type="Medal"},

	{byte=0x49, bit=0, name="Castle: Chunky Banana Medal", type="Medal"},
	{byte=0x49, bit=1, name="Helm: DK Banana Medal", type="Medal", map=17},
	{byte=0x49, bit=2, name="Helm: Diddy Banana Medal", type="Medal", map=17},
	{byte=0x49, bit=3, name="Helm: Lanky Banana Medal", type="Medal", map=17},
	{byte=0x49, bit=4, name="Helm: Tiny Banana Medal", type="Medal", map=17},
	{byte=0x49, bit=5, name="Helm: Chunky Banana Medal", type="Medal", map=17},
	{byte=0x49, bit=6, name="Japes: Fairy (Water room)", type="Fairy", map=7},
	{byte=0x49, bit=7, name="Japes: Fairy (Painting room)", type="Fairy", map=13},

	{byte=0x4A, bit=0, name="Factory: Fairy (Funky)", type="Fairy", map=26},
	{byte=0x4A, bit=1, name="Galleon: Fairy (Chunky's chest room)", type="Fairy", map=30},
	{byte=0x4A, bit=2, name="Isles: Fairy (Factory Lobby)", type="Fairy", map=175},
	{byte=0x4A, bit=3, name="Isles: Fairy (Fungi Lobby)", type="Fairy", map=178},
	{byte=0x4A, bit=4, name="Fungi: Fairy (Diddy's Barn)", type="Fairy", map=56},
	{byte=0x4A, bit=5, name="Fungi: Fairy (DK's Barn)", type="Fairy", map=59},
	{byte=0x4A, bit=6, name="Caves: Fairy (Tiny 5DI)", type="Fairy", map=84},
	{byte=0x4A, bit=7, name="Helm: Fairy (1)", type="Fairy", map=17},

	{byte=0x4B, bit=0, name="Helm: Fairy (2)", type="Fairy", map=17},
	{byte=0x4B, bit=1, name="Aztec: Fairy (Llama Temple)", type="Fairy", map=20},
	{byte=0x4B, bit=2, name="Aztec: Fairy (Tiny 5DT)", type="Fairy", map=22},
	{byte=0x4B, bit=3, name="Factory: Fairy (Number Game area)", type="Fairy", map=26},
	{byte=0x4B, bit=4, name="Galleon: Fairy (Tiny 5DS)", type="Fairy", map=46},
	{byte=0x4B, bit=5, name="Castle: Fairy (Museum)", type="Fairy", map=113},
	{byte=0x4B, bit=6, name="Castle: Fairy (Tree)", type="Fairy", map=164},
	{byte=0x4B, bit=7, name="Isles: Fairy (Tree)", type="Fairy", map=34},

	{byte=0x4C, bit=0, name="Isles: Fairy (High)", type="Fairy", map=34},
	{byte=0x4C, bit=1, name="Caves: Fairy (Diddy Cabin)", type="Fairy", map=200},
	{byte=0x4C, bit=2, name="Japes: Crown", type="Crown", map=53},
	{byte=0x4C, bit=3, name="Aztec: Crown", type="Crown", map=73},
	{byte=0x4C, bit=4, name="Factory: Crown", type="Crown", map=155},
	{byte=0x4C, bit=5, name="Galleon: Crown", type="Crown", map=156},
	{byte=0x4C, bit=6, name="Fungi: Crown", type="Crown", map=159},
	{byte=0x4C, bit=7, name="Isles: Crown (Fungi Lobby)", type="Crown", map=157},

	{byte=0x4D, bit=0, name="Isles: Crown (Snide's)", type="Crown", map=158},
	{byte=0x4D, bit=1, name="Caves: Crown", type="Crown", map=160},
	{byte=0x4D, bit=2, name="Castle: Crown", type="Crown", map=161},
	{byte=0x4D, bit=3, name="Helm: Crown", type="Crown", map=162},
	{byte=0x4D, bit=5, name="Diddy CB: Japes: Inside Mountain Balloon", type="Balloon"},
	{byte=0x4D, bit=6, name="Lanky CB: Japes: Kasplat Balloon", type="Balloon"},
	{byte=0x4D, bit=7, name="Chunky CB: Japes: Rambi Area Balloon (1)", type="Balloon"},

	{byte=0x4E, bit=0, name="Chunky CB: Japes: Rambi Area Balloon (2)", type="Balloon"},
	{byte=0x4E, bit=1, name="Tiny CB: Japes: Rambi Area Balloon", type="Balloon"},
	{byte=0x4E, bit=2, name="Tiny CB: Japes: Hut Balloon", type="Balloon"},
	{byte=0x4E, bit=3, name="DK CB: Japes: Cranky Balloon", type="Balloon"},
	{byte=0x4E, bit=4, name="DK CB: Japes: Near Baboon Blast Balloon", type="Balloon"},
	{byte=0x4E, bit=5, name="Diddy CB: Japes: Mountain Balloon", type="Bunch"},
	{byte=0x4E, bit=6, name="Lanky CB: Japes: Hut Balloon", type="Balloon"},
	{byte=0x4E, bit=7, name="Chunky CB: Japes: Rambi Area Balloon (3)", type="Balloon"},

	{byte=0x4F, bit=0, name="DK CB: Japes: Snide's Balloon", type="Balloon"},
	{byte=0x4F, bit=1, name="Diddy CB: Japes: Cave Balloon", type="Balloon"},
	{byte=0x4F, bit=2, name="Japes: Rainbow Coin (Slope)", type="Rainbow Coin"},
	{byte=0x4F, bit=3, name="Tiny CB: Japes: Shellhive Balloon", type="Balloon"},
	{byte=0x4F, bit=4, name="Lanky CB: Japes: Painting Balloon", type="Balloon"},

	{byte=0x50, bit=7, name="Aztec: Rainbow Coin (5DT)", type="Rainbow Coin"},

	{byte=0x52, bit=6, name="Factory: Rainbow Coin (Dark Room)", type="Rainbow Coin"},

	{byte=0x54, bit=5, name="Isles: Rainbow Coin (Fungi Isle)", type="Rainbow Coin"},
	{byte=0x54, bit=7, name="Isles: Rainbow Coin (Aztec Roof)", type="Rainbow Coin"},

	{byte=0x55, bit=1, name="Aztec: Rainbow Coin (Oasis)", type="Rainbow Coin"},

	{byte=0x56, bit=1, name="Fungi: Rainbow Coin (Beanstalk)", type="Rainbow Coin"},
	{byte=0x56, bit=7, name="Galleon: Rainbow Coin (Lighthouse)", type="Rainbow Coin"},

	{byte=0x58, bit=3, name="Caves: Rainbow Coin (Giant Kosha)", type="Rainbow Coin"},

	{byte=0x59, bit=2, name="Castle: Rainbow Coin (Snide's)", type="Rainbow Coin"},
	{byte=0x59, bit=7, name="Isles: Rainbow Coin (K-Lumsy)", type="Rainbow Coin"},

	{byte=0x5C, bit=0, name="Training Grounds: Rainbow Coin (Rear)", type="Rainbow Coin"},
	{byte=0x5C, bit=1, name="Training Grounds: Rainbow Coin (Banana Hoard)", type="Rainbow Coin"},
	{byte=0x5C, bit=4, name="Isles: Rainbow Coin (Castle Lobby)", type="Rainbow Coin"},

	{byte=0x60, bit=6, name="Helm: Warp 1 (Near)", type="Warp"},
	{byte=0x60, bit=7, name="Helm: Warp 1 (Far)", type="Warp"},

	{byte=0x61, bit=7, name="Fungi: Story Cutscene", type="Cutscene"},

	{byte=0x64, bit=1, name="Chunky Coin: Japes: Underwater (1)", type="Coin"},
	{byte=0x64, bit=2, name="Tiny CB: Japes: Starting Tunnel (1)", type="CB"},
	{byte=0x64, bit=3, name="Tiny CB: Japes: Starting Tunnel (2)", type="CB"},
	{byte=0x64, bit=4, name="Tiny CB: Japes: Starting Tunnel (3)", type="CB"},
	{byte=0x64, bit=5, name="Chunky CB: Japes: Kasplat's Tunnel (1)", type="CB"},
	{byte=0x64, bit=6, name="Tiny CB: Japes: Starting Tunnel (4)", type="CB"},
	{byte=0x64, bit=7, name="DK CB: Japes: Right W3 Bunch", type="Bunch"},

	{byte=0x65, bit=0, name="DK CB: Japes: Starting Vines (1)", type="CB"},
	{byte=0x65, bit=1, name="Lanky CB: Japes: Kasplat", type="Bunch"},
	{byte=0x65, bit=2, name="DK CB: Japes: Left W3 Bunch", type="Bunch"},
	{byte=0x65, bit=3, name="Diddy CB: Japes: Starting Area (1)", type="CB"},
	{byte=0x65, bit=4, name="DK CB: Japes: Starting Vines (2)", type="CB"},
	{byte=0x65, bit=5, name="Diddy CB: Japes: Starting Area (2)", type="CB"},
	{byte=0x65, bit=6, name="Chunky CB: Japes: Funky Bunch (1)", type="Bunch"},
	{byte=0x65, bit=7, name="Lanky CB: Japes: Cranky Bunch", type="Bunch"},

	{byte=0x66, bit=0, name="Diddy CB: Japes: Mountain Stream (1)", type="CB"},
	{byte=0x66, bit=1, name="Diddy CB: Japes: Mountain Stream (2)", type="CB"},
	{byte=0x66, bit=2, name="Diddy CB: Japes: Conveyor Bunch", type="Bunch"},
	{byte=0x66, bit=4, name="Diddy CB: Japes: Mountain Peanut Switch", type="Bunch"},
	{byte=0x66, bit=5, name="DK CB: Japes: Starting Vines (3)", type="CB"},
	{byte=0x66, bit=6, name="DK CB: Japes: Starting Vines (4)", type="CB"},
	{byte=0x66, bit=7, name="DK CB: Japes: Starting Vines (5)", type="CB"},

	{byte=0x67, bit=1, name="Diddy Coin: Japes: Under Conveyor", type="Coin"},
	{byte=0x67, bit=2, name="Diddy Coin: Japes: Mountain Bridge", type="Coin"},
	{byte=0x67, bit=3, name="Diddy CB: Japes: Minecart Bunch", type="Bunch"},
	{byte=0x67, bit=4, name="Diddy Coin: Japes: Coal Pile", type="Coin"},
	{byte=0x67, bit=5, name="Diddy CB: Japes: Mountain Stream (3)", type="CB"},
	{byte=0x67, bit=6, name="Diddy CB: Japes: Mountain Stream (4)", type="CB"},
	{byte=0x67, bit=7, name="Diddy CB: Japes: Mountain Stream (5)", type="CB"},

	{byte=0x68, bit=1, name="Lanky CB: Japes: Kasplat (1)", type="CB"},
	{byte=0x68, bit=2, name="Chunky Coin: Japes: Underwater (2)", type="Coin"},
	{byte=0x68, bit=3, name="Chunky Coin: Japes: Underwater (3)", type="Coin"},
	{byte=0x68, bit=4, name="Diddy CB: Japes: Hut Bunch", type="Bunch"},
	{byte=0x68, bit=5, name="Lanky CB: Japes: Kasplat (2)", type="CB"},
	{byte=0x68, bit=6, name="Japes: DK CB: OOBB under Rambi Box", type="CB", map=7},
	{byte=0x68, bit=7, name="Lanky Coin: Japes: Cave (1)", type="Coin"},

	{byte=0x69, bit=0, name="Diddy Coin: Japes: Cave (1)", type="Coin"},
	{byte=0x69, bit=1, name="Tiny Coin: Japes: Rambi Area (1)", type="Coin"},
	{byte=0x69, bit=2, name="DK Coin: Japes: Rambi Box (1)", type="Coin"},
	{byte=0x69, bit=3, name="DK CB: Japes: Cranky Tunnel (1)", type="CB"},
	{byte=0x69, bit=4, name="DK CB: Japes: Cranky Tunnel (2)", type="CB"},
	{byte=0x69, bit=5, name="DK CB: Japes: Cranky Tunnel (3)", type="CB"},
	{byte=0x69, bit=6, name="Lanky CB: Japes: Hut Bunch", type="Bunch"},
	{byte=0x69, bit=7, name="DK CB: Japes: Hut Bunch", type="Bunch"},

	{byte=0x6A, bit=0, name="DK CB: Japes: Mountain (1)", type="CB"},
	{byte=0x6A, bit=1, name="Lanky CB: Japes: Cave Bunch", type="Bunch"},
	{byte=0x6A, bit=2, name="Diddy CB: Japes: Starting Area (3)", type="CB"},
	{byte=0x6A, bit=3, name="DK CB: Japes: Cranky Tunnel (4)", type="CB"},
	{byte=0x6A, bit=4, name="DK CB: Japes: Cranky Tunnel (5)", type="CB"},
	{byte=0x6A, bit=5, name="Diddy CB: Japes: Kasplat (1)", type="CB"},
	{byte=0x6A, bit=6, name="DK CB: Japes: Cranky Tunnel (6)", type="CB"},
	{byte=0x6A, bit=7, name="DK CB: Japes: Cranky Tunnel (7)", type="CB"},

	{byte=0x6B, bit=0, name="DK Coin: Japes: Around Baboon Blast (1)", type="Coin"},
	{byte=0x6B, bit=1, name="DK CB: Japes: Mountain (2)", type="CB"},
	{byte=0x6B, bit=2, name="DK CB: Japes: Mountain (3)", type="CB"},
	{byte=0x6B, bit=3, name="DK CB: Japes: Mountain (4)", type="CB"},
	{byte=0x6B, bit=4, name="DK Coin: Japes: Start Gate (1)", type="CB"},
	{byte=0x6B, bit=5, name="Chunky CB: Japes: Kasplat's Tunnel (2)", type="CB"},
	{byte=0x6B, bit=6, name="DK CB: Japes: Mountain (5)", type="CB"},
	{byte=0x6B, bit=7, name="DK CB: Japes: Mountain (6)", type="CB"},

	{byte=0x6C, bit=0, name="Chunky CB: Japes: Kasplat's Tunnel (3)", type="CB"},
	{byte=0x6C, bit=1, name="Lanky Coin: Japes: Kasplat Coin (1)", type="Coin"},
	{byte=0x6C, bit=2, name="Diddy Coin: Japes: Cave (2)", type="Coin"},
	{byte=0x6C, bit=3, name="DK CB: Japes: Cranky Tunnel (8)", type="CB"},
	{byte=0x6C, bit=4, name="DK CB: Japes: Troff 'n' Scoff Bunch", type="Bunch"},
	{byte=0x6C, bit=5, name="DK CB: Japes: Cranky Tunnel (9)", type="CB"},
	{byte=0x6C, bit=6, name="DK CB: Japes: Funky Tree", type="Bunch"},
	{byte=0x6C, bit=7, name="Diddy Coin: Japes: Cannon (1)", type="Coin"},

	{byte=0x6D, bit=0, name="Chunky CB: Japes: Shellhive Tree Bunch (1)", type="Bunch"},
	{byte=0x6D, bit=1, name="Tiny Coin: Japes: Rambi Area (2)", type="Coin"},
	{byte=0x6D, bit=2, name="Diddy Coin: Japes: Cannon (2)", type="Coin"},
	{byte=0x6D, bit=3, name="Diddy CB: Japes: Kasplat (2)", type="CB"},
	{byte=0x6D, bit=4, name="Diddy CB: Japes: Kasplat (3)", type="CB"},
	{byte=0x6D, bit=5, name="DK CB: Japes: Cannon Tree Bunch", type="Bunch"},
	{byte=0x6D, bit=6, name="DK Coin: Japes: Around Baboon Blast (2)", type="Coin"},
	{byte=0x6D, bit=7, name="DK Coin: Japes: Start Gate (2)", type="CB"},

	{byte=0x6E, bit=0, name="Tiny CB: Japes: Hut Bunch", type="Bunch"},
	{byte=0x6E, bit=1, name="DK Coin: Japes: Rambi Box (2)", type="Coin"},
	{byte=0x6E, bit=2, name="DK Coin: Japes: Diddy Kasplat", type="Coin"},
	{byte=0x6E, bit=3, name="DK Coin: Japes: Kasplat (1)", type="Coin"},
	{byte=0x6E, bit=4, name="Tiny Coin: Japes: Kasplat (1)", type="Coin"},
	{byte=0x6E, bit=5, name="Diddy CB: Japes: Front Tree Bunch (1)", type="Bunch"},
	{byte=0x6E, bit=6, name="Diddy CB: Japes: Front Tree Bunch (2)", type="Bunch"},
	{byte=0x6E, bit=7, name="DK CB: Japes: Rambi Bunch", type="Bunch"},

	{byte=0x6F, bit=0, name="Lanky Coin: Japes: Cave (2)", type="Coin"},
	{byte=0x6F, bit=1, name="Lanky Coin: Japes: Cave (3)", type="Coin"},
	{byte=0x6F, bit=2, name="Diddy Coin: Japes: Kasplat (1)", type="Coin"},
	{byte=0x6F, bit=3, name="Chunky CB: Japes: Kasplat's Tunnel (4)", type="CB"},
	{byte=0x6F, bit=4, name="Diddy CB: Japes: Around Mountain (1)", type="CB"},
	{byte=0x6F, bit=5, name="Diddy CB: Japes: Starting Area (4)", type="CB"},
	{byte=0x6F, bit=6, name="Tiny Coin: Japes: Kasplat (2)", type="Coin"},
	{byte=0x6F, bit=7, name="DK Coin: Japes: Start Gate (3)", type="CB"},

	{byte=0x70, bit=0, name="Tiny CB: Japes: Left Log (1)", type="Bunch"},
	{byte=0x70, bit=1, name="Tiny CB: Japes: Left Log (2)", type="Bunch"},
	{byte=0x70, bit=2, name="Tiny CB: Japes: Left Log (3)", type="Bunch"},
	{byte=0x70, bit=3, name="Tiny CB: Japes: Right Log (1)", type="Bunch"},
	{byte=0x70, bit=4, name="Tiny CB: Japes: Right Log (2)", type="Bunch"},
	{byte=0x70, bit=5, name="Tiny CB: Japes: Right Log (3)", type="Bunch"},
	{byte=0x70, bit=6, name="DK CB: Japes: Diddy Cage Tree Bunch", type="Bunch"},
	{byte=0x70, bit=7, name="Tiny CB: Japes: Front of Shellhive", type="Bunch"},

	{byte=0x71, bit=0, name="Diddy CB: Japes: Around Mountain (2)", type="CB"},
	{byte=0x71, bit=1, name="Diddy CB: Japes: Around Mountain (3)", type="CB"},
	{byte=0x71, bit=2, name="Diddy CB: Japes: Around Mountain (4)", type="CB"},
	{byte=0x71, bit=3, name="Chunky CB: Japes: Kasplat's Tunnel (5)", type="CB"},
	{byte=0x71, bit=4, name="Chunky CB: Japes: Kasplat's Tunnel (6)", type="CB"},
	{byte=0x71, bit=5, name="Chunky CB: Japes: Kasplat's Tunnel (7)", type="CB"},
	{byte=0x71, bit=6, name="Chunky CB: Japes: Kasplat's Tunnel (8)", type="CB"},
	{byte=0x71, bit=7, name="Chunky CB: Japes: Kasplat's Tunnel (9)", type="CB"},

	{byte=0x72, bit=0, name="Diddy CB: Japes: Underwater Bunch (1)", type="Bunch"},
	{byte=0x72, bit=1, name="Diddy Coin: Japes: Cave (3)", type="Coin"},
	{byte=0x72, bit=2, name="Diddy CB: Japes: Underwater Bunch (2)", type="Bunch"},
	{byte=0x72, bit=3, name="Diddy CB: Japes: Right Tree Bunch (1)", type="Bunch"},
	{byte=0x72, bit=4, name="Diddy Coin: Japes: Kasplat (2)", type="Coin"},
	{byte=0x72, bit=5, name="Diddy CB: Japes: Right Tree Bunch (2)", type="Bunch"},
	{byte=0x72, bit=6, name="Diddy CB: Japes: Around Mountain (5)", type="CB"},
	{byte=0x72, bit=7, name="Diddy CB: Japes: Around Mountain (6)", type="CB"},

	{byte=0x73, bit=0, name="Tiny CB: Japes: Starting Tunnel (5)", type="CB"},
	{byte=0x73, bit=1, name="DK Coin: Japes: Around Baboon Blast (3)", type="Coin"},
	{byte=0x73, bit=3, name="Tiny CB: Japes: Rambi Area (1)", type="CB"},
	{byte=0x73, bit=4, name="Tiny CB: Japes: Rambi Area (2)", type="CB"},
	{byte=0x73, bit=5, name="Lanky Coin: Japes: Underwater (1)", type="Coin"},
	{byte=0x73, bit=6, name="Lanky Coin: Japes: Underwater (2)", type="Coin"},
	{byte=0x73, bit=7, name="Tiny CB: Japes: Rambi Area (3)", type="CB"},

	{byte=0x74, bit=0, name="Lanky CB: Japes: Kasplat (3)", type="CB"},
	{byte=0x74, bit=1, name="Lanky CB: Japes: Rambi Cave (1)", type="CB"},
	{byte=0x74, bit=2, name="Lanky CB: Japes: Rambi Cave (2)", type="CB"},
	{byte=0x74, bit=3, name="Lanky CB: Japes: Rambi Cave (3)", type="CB"},
	{byte=0x74, bit=4, name="Lanky CB: Japes: Snide's Tree", type="Bunch"},
	{byte=0x74, bit=5, name="Chunky CB: Japes: Funky Bunch (2)", type="Bunch"},
	{byte=0x74, bit=6, name="Diddy CB: Japes: Starting Area (5)", type="CB"},
	{byte=0x74, bit=7, name="Lanky Coin: Japes: Kasplat Coin (2)", type="Coin"},

	{byte=0x75, bit=0, name="Lanky CB: Japes: Painting Hill (1)", type="CB"},
	{byte=0x75, bit=1, name="Lanky CB: Japes: Painting Hill (2)", type="CB"},
	{byte=0x75, bit=2, name="Lanky CB: Japes: Underwater (1)", type="CB"},
	{byte=0x75, bit=3, name="Lanky CB: Japes: Underwater (2)", type="CB"},
	{byte=0x75, bit=4, name="Lanky CB: Japes: Underwater (3)", type="CB"},
	{byte=0x75, bit=5, name="Lanky CB: Japes: Underwater (4)", type="CB"},
	{byte=0x75, bit=6, name="Lanky CB: Japes: Underwater (5)", type="CB"},
	{byte=0x75, bit=7, name="Lanky CB: Japes: Rambi Cave (4)", type="CB"},

	{byte=0x76, bit=2, name="Lanky CB: Japes: Kasplat (4)", type="CB"},
	{byte=0x76, bit=3, name="Lanky CB: Japes: Kasplat (5)", type="CB"},
	{byte=0x76, bit=4, name="Lanky CB: Japes: Kasplat (6)", type="CB"},
	{byte=0x76, bit=5, name="Lanky CB: Japes: Rambi Cave (5)", type="CB"},
	{byte=0x76, bit=6, name="Lanky CB: Japes: Kasplat (7)", type="CB"},
	{byte=0x76, bit=7, name="Lanky CB: Japes: Painting Hill (3)", type="CB"},

	{byte=0x77, bit=0, name="Tiny CB: Japes: Cranky Bunch", type="Bunch"},
	{byte=0x77, bit=1, name="Tiny CB: Japes: Cave Bunch", type="Bunch"},
	{byte=0x77, bit=2, name="Diddy Coin: Japes: Underwater Coin (1)", type="Coin"},
	{byte=0x77, bit=3, name="Chunky CB: Japes: Kasplat's Tunnel (10)", type="CB"},
	{byte=0x77, bit=4, name="Diddy Coin: Japes: Underwater Coin (2)", type="Coin"},
	{byte=0x77, bit=5, name="Diddy Coin: Japes: Underwater Coin (3)", type="Coin"},
	{byte=0x77, bit=6, name="Chunky Coin: Japes: Stump (1)", type="Coin"},
	{byte=0x77, bit=7, name="Chunky Coin: Japes: Stump (2)", type="Coin"},

	{byte=0x78, bit=0, name="Chunky CB: Japes: Near Baboon Blast (1)", type="CB"},
	{byte=0x78, bit=1, name="Chunky CB: Japes: Cranky Area", type="Bunch"},
	{byte=0x78, bit=2, name="Lanky Coin: Japes: Snide's (1)", type="Coin"},
	{byte=0x78, bit=3, name="Lanky CB: Japes: Snide's", type="Bunch"},
	{byte=0x78, bit=4, name="Lanky Coin: Japes: Snide's (2)", type="Coin"},
	{byte=0x78, bit=5, name="Lanky Coin: Japes: Snide's (3)", type="Coin"},
	{byte=0x78, bit=6, name="DK Coin: Japes: Kasplat (2)", type="Coin"},
	{byte=0x78, bit=7, name="Tiny Coin: Japes: Kasplat (3)", type="Coin"},

	{byte=0x79, bit=0, name="Tiny CB: Japes: Rambi Area (4)", type="CB"},
	{byte=0x79, bit=1, name="Tiny CB: Japes: Rambi Area (5)", type="CB"},
	{byte=0x79, bit=2, name="Tiny CB: Japes: Rambi Area (6)", type="CB"},
	{byte=0x79, bit=3, name="Diddy CB: Japes: Around Mountain (7)", type="CB"},
	{byte=0x79, bit=4, name="Chunky CB: Japes: Near Baboon Blast (2)", type="CB"},
	{byte=0x79, bit=5, name="Chunky CB: Japes: Near Baboon Blast (3)", type="CB"},
	{byte=0x79, bit=6, name="Chunky CB: Japes: Near Baboon Blast (4)", type="CB"},
	{byte=0x79, bit=7, name="Chunky CB: Japes: Near Baboon Blast (5)", type="CB"},

	{byte=0x7A, bit=2, name="Tiny Coin: Japes: Rambi Area (3)", type="Coin"},
	{byte=0x7A, bit=3, name="Tiny Coin: Japes: Rambi Area (4)", type="Coin"},
	{byte=0x7A, bit=4, name="Tiny Coin: Japes: Rambi Area (5)", type="Coin"},
	{byte=0x7A, bit=5, name="Chunky CB: Japes: Shellhive Tree Bunch (2)", type="Bunch"},
	{byte=0x7A, bit=6, name="Chunky CB: Japes: Shellhive Tree Bunch (3)", type="Bunch"},
	{byte=0x7A, bit=7, name="Tiny CB: Japes: Rambi Area (7)", type="CB"},

	{byte=0x7B, bit=0, name="Lanky Coin: Japes: Kasplat Coin (3)", type="Coin"},
	{byte=0x7B, bit=1, name="Chunky CB: Japes: Shellhive Tree Bunch (4)", type="Bunch"},
	{byte=0x7B, bit=2, name="Chunky Coin: Japes: Stump (3)", type="Coin"},
	{byte=0x7B, bit=3, name="Diddy Coin: Japes: Kasplat (3)", type="Coin"},
	{byte=0x7B, bit=4, name="Lanky Coin: Japes: Snide's (4)", type="Coin"},
	{byte=0x7B, bit=5, name="Lanky Coin: Japes: Snide's (5)", type="Coin"},
	{byte=0x7B, bit=6, name="DK Coin: Japes: Rambi Box (3)", type="Coin"},

	{byte=0x7C, bit=0, name="Tiny Coin: Japes: Underground (1)", type="Coin"},
	{byte=0x7C, bit=1, name="Chunky CB: Japes: Underground Bunch (1)", type="Bunch"},
	{byte=0x7C, bit=2, name="Chunky CB: Japes: Underground Bunch (2)", type="Bunch"},
	{byte=0x7C, bit=3, name="Tiny Coin: Japes: Underground (2)", type="Coin"},
	{byte=0x7C, bit=4, name="Chunky Coin: Japes: Underground (1)", type="Coin"},
	{byte=0x7C, bit=5, name="Chunky Coin: Japes: Underground (2)", type="Coin"},
	{byte=0x7C, bit=6, name="DK CB: Japes: Baboon Blast Bunch (1)", type="Bunch"},
	{byte=0x7C, bit=7, name="DK Coin: Japes: Baboon Blast (1)", type="Coin"},

	{byte=0x7D, bit=0, name="Lanky CB: Japes: Painting Pegs (1)", type="Bunch"},
	{byte=0x7D, bit=1, name="Tiny Coin: Japes: Underground (3)", type="Coin"},
	{byte=0x7D, bit=2, name="Chunky Coin: Japes: Underground (3)", type="Coin"},
	{byte=0x7D, bit=3, name="Chunky CB: Japes: Underground (1)", type="CB"},
	{byte=0x7D, bit=4, name="Chunky CB: Japes: Underground (2)", type="CB"},
	{byte=0x7D, bit=5, name="Chunky CB: Japes: Underground (3)", type="CB"},
	{byte=0x7D, bit=6, name="Chunky CB: Japes: Underground (4)", type="CB"},
	{byte=0x7D, bit=7, name="Chunky CB: Japes: Underground (5)", type="CB"},

	{byte=0x7E, bit=0, name="Tiny CB: Japes: Shellhive Podium (1)", type="CB"},
	{byte=0x7E, bit=1, name="Tiny CB: Japes: Shellhive Podium (2)", type="CB"},
	{byte=0x7E, bit=2, name="Tiny CB: Japes: Shellhive Podium (3)", type="CB"},
	{byte=0x7E, bit=3, name="Lanky CB: Japes: Painting Pegs (2)", type="Bunch"},
	{byte=0x7E, bit=4, name="Lanky CB: Japes: Painting Stairs (1)", type="Bunch"},
	{byte=0x7E, bit=5, name="Lanky Coin: Japes: Painting Room (1)", type="Coin"},
	{byte=0x7E, bit=6, name="Lanky Coin: Japes: Painting Room (2)", type="Coin"},
	{byte=0x7E, bit=7, name="Lanky CB: Japes: Painting Stairs (2)", type="Bunch"},

	{byte=0x7F, bit=0, name="DK Coin: Japes: Kasplat (3)", type="Coin"},
	{byte=0x7F, bit=1, name="Tiny Coin: Japes: Shellhive (1)", type="Coin"},
	{byte=0x7F, bit=2, name="Tiny Coin: Japes: Shellhive (2)", type="Coin"},
	{byte=0x7F, bit=3, name="Tiny CB: Japes: Shellhive Podium (4)", type="CB"},
	{byte=0x7F, bit=4, name="Tiny CB: Japes: Shellhive Podium (5)", type="CB"},
	{byte=0x7F, bit=5, name="Tiny CB: Japes: Shellhive Podium (6)", type="CB"},
	{byte=0x7F, bit=6, name="Tiny CB: Japes: Shellhive Podium (7)", type="CB"},
	{byte=0x7F, bit=7, name="Tiny CB: Japes: Shellhive Podium (8)", type="CB"},

	{byte=0x83, bit=0, name="DK Coin: Japes: Baboon Blast (2)", type="Coin"},
	{byte=0x83, bit=1, name="DK CB: Japes: Baboon Blast Bunch (2)", type="Bunch"},

	{byte=0xE1, bit=3, name="Fungi: Lower Warp 5", type="Bunch"},
	{byte=0xE1, bit=2, name="Fungi: Upper Warp 5", type="Bunch"},

	{byte=0x101, bit=2, name="Caves: Warp 1 Bunch (Base)", type="Bunch"},
};

return flag_array;