local flag_array = {
	{["byte"] = 0x0, ["bit"] = 4, ["name"] = "Japes: DK GB: In front of Diddy's cage", ["type"] = "GB", ["map"] = 7},
	{["byte"] = 0x0, ["bit"] = 6, ["name"] = "Kong Unlocked: Diddy", ["type"] = "Kong", ["map"] = 7},

	{["byte"] = 0x3, ["bit"] = 2, ["name"] = "Key 1", ["type"] = "Key", ["map"] = 8},

	{["byte"] = 0x5, ["bit"] = 6, ["name"] = "Japes: T&S Cleared", ["type"] = "T&S", ["map"] = 7},

	{["byte"] = 0x8, ["bit"] = 3, ["name"] = "Kong Unlocked: Tiny", ["type"] = "Kong", ["map"] = 16},
	{["byte"] = 0x8, ["bit"] = 4, ["name"] = "Aztec: Diddy GB: Tiny's Cage", ["type"] = "GB", ["map"] = 16},
	{["byte"] = 0x8, ["bit"] = 7, ["name"] = "Kong Unlocked: Lanky", ["type"] = "Kong", ["map"] = 20},

	{["byte"] = 0x9, ["bit"] = 3, ["name"] = "Key 2", ["type"] = "Key", ["map"] = 197},
	{["byte"] = 0x9, ["bit"] = 6, ["name"] = "Aztec: DK GB: Free Lanky", ["type"] = "GB", ["map"] = 20},

	{["byte"] = 0xB, ["bit"] = 1, ["name"] = "Aztec: W1 (Llama temple, high)", ["type"] = "Warp", ["map"] = 20},
	{["byte"] = 0xB, ["bit"] = 2, ["name"] = "Aztec: W1 (Llama temple, low)", ["type"] = "Warp", ["map"] = 20},
	{["byte"] = 0xB, ["bit"] = 3, ["name"] = "Aztec: W2 (Llama temple, far)", ["type"] = "Warp", ["map"] = 20},
	{["byte"] = 0xB, ["bit"] = 4, ["name"] = "Aztec: W2 (Llama temple, low)", ["type"] = "Warp", ["map"] = 20},
	{["byte"] = 0xB, ["bit"] = 6, ["name"] = "Aztec: Lanky's help me cutscene", ["type"] = "Cutscene", ["map"] = 20},
	{["byte"] = 0xB, ["bit"] = 7, ["name"] = "Aztec: Tiny's help me cutscene", ["type"] = "Cutscene", ["map"] = 16},

	{["byte"] = 0xE, ["bit"] = 6, ["name"] = "Kong Unlocked: Chunky", ["type"] = "Kong", ["map"] = 26},
	{["byte"] = 0xE, ["bit"] = 7, ["name"] = "Factory: Lanky GB: Free Chunky", ["type"] = "GB", ["map"] = 26},

	{["byte"] = 0x11, ["bit"] = 3, ["name"] = "Key 3", ["type"] = "Key", ["map"] = 154},
	{["byte"] = 0x11, ["bit"] = 5, ["name"] = "Factory: Chunky's help me cutscene", ["type"] = "Cutscene", ["map"] = 26},

	{["byte"] = 0x15, ["bit"] = 1, ["name"] = "Key 4", ["type"] = "Key", ["map"] = 111},

	{["byte"] = 0x19, ["bit"] = 4, ["name"] = "Galleon: T&S Cleared", ["type"] = "T&S", ["map"] = 30},

	{["byte"] = 0x1D, ["bit"] = 5, ["name"] = "Key 5", ["type"] = "Key", ["map"] = {83, 197}},

	{["byte"] = 0x24, ["bit"] = 5, ["name"] = "Key 6", ["type"] = "Key", ["map"] = 196},

	{["byte"] = 0x25, ["bit"] = 7, ["name"] = "Caves: T&S Cleared", ["type"] = "T&S", ["map"] = 72},

	{["byte"] = 0x27, ["bit"] = 6, ["name"] = "Key 7", ["type"] = "Key", ["map"] = 199},

	{["byte"] = 0x2C, ["bit"] = 1, ["name"] = "Castle: T&S Cleared", ["type"] = "T&S", ["map"] = 87},
	{["byte"] = 0x2C, ["bit"] = 4, ["name"] = "Warp pad FTT", ["type"] = "FTT"},

	{["byte"] = 0x2F, ["bit"] = 2, ["name"] = "Camera/Shockwave", ["map"] = 189},
	{["byte"] = 0x2F, ["bit"] = 5, ["name"] = "Key 8", ["type"] = "Key", ["map"] = 17},

	{["byte"] = 0x30, ["bit"] = 2, ["name"] = "Kong Unlocked: DK", ["type"] = "Kong"},

	{["byte"] = 0x36, ["bit"] = 2, ["name"] = "Isles: W1 (Ring)", ["type"] = "Warp", ["map"] = 34},
	{["byte"] = 0x36, ["bit"] = 3, ["name"] = "Isles: W1 (Far)", ["type"] = "Warp", ["map"] = 34},
	{["byte"] = 0x36, ["bit"] = 4, ["name"] = "Isles: W2 (Ring)", ["type"] = "Warp", ["map"] = 34},
	{["byte"] = 0x36, ["bit"] = 5, ["name"] = "Isles: W2 (High)", ["type"] = "Warp", ["map"] = 34},
	{["byte"] = 0x36, ["bit"] = 6, ["name"] = "Isles: W3 (Ring)", ["type"] = "Warp", ["map"] = 34},
	{["byte"] = 0x36, ["bit"] = 7, ["name"] = "Isles: W3 (Far)", ["type"] = "Warp", ["map"] = 34},

	{["byte"] = 0x37, ["bit"] = 0, ["name"] = "Isles: W4 (Ring)", ["type"] = "Warp", ["map"] = 34},
	{["byte"] = 0x37, ["bit"] = 1, ["name"] = "Isles: W4 (High)", ["type"] = "Warp", ["map"] = 34},
	{["byte"] = 0x37, ["bit"] = 2, ["name"] = "Isles: W5 (Far)", ["type"] = "Warp", ["map"] = 34},
	{["byte"] = 0x37, ["bit"] = 3, ["name"] = "Isles: W5 (Ring)", ["type"] = "Warp", ["map"] = 34},

	{["byte"] = 0x37, ["bit"] = 5, ["name"] = "Key 1 Turned", ["type"] = "Key", ["map"] = {34,97}},
	{["byte"] = 0x37, ["bit"] = 6, ["name"] = "Key 2 Turned", ["type"] = "Key", ["map"] = {34,97}},
	{["byte"] = 0x37, ["bit"] = 7, ["name"] = "Key 3 Turned", ["type"] = "Key", ["map"] = {34,97}},

	{["byte"] = 0x38, ["bit"] = 0, ["name"] = "Key 4 Turned", ["type"] = "Key", ["map"] = {34,97}},
	{["byte"] = 0x38, ["bit"] = 1, ["name"] = "Key 5 Turned", ["type"] = "Key", ["map"] = {34,97}},
	{["byte"] = 0x38, ["bit"] = 2, ["name"] = "Key 6 Turned", ["type"] = "Key", ["map"] = {34,97}},
	{["byte"] = 0x38, ["bit"] = 3, ["name"] = "Key 7 Turned", ["type"] = "Key", ["map"] = {34,97}},
	{["byte"] = 0x38, ["bit"] = 4, ["name"] = "Key 8 Turned", ["type"] = "Key", ["map"] = {34,97}},

	{["byte"] = 0x3A, ["bit"] = 6, ["name"] = "Japes: DK Blueprint", ["type"] = "Blueprint", ["map"] = 7},
	{["byte"] = 0x3A, ["bit"] = 7, ["name"] = "Japes: Diddy Blueprint", ["type"] = "Blueprint", ["map"] = 7},

	{["byte"] = 0x3B, ["bit"] = 0, ["name"] = "Japes: Lanky Blueprint", ["type"] = "Blueprint", ["map"] = 7},
	{["byte"] = 0x3B, ["bit"] = 1, ["name"] = "Japes: Tiny Blueprint", ["type"] = "Blueprint", ["map"] = 7},
	{["byte"] = 0x3B, ["bit"] = 2, ["name"] = "Japes: Chunky Blueprint", ["type"] = "Blueprint", ["map"] = 33},
	{["byte"] = 0x3B, ["bit"] = 3, ["name"] = "Aztec: DK Blueprint", ["type"] = "Blueprint", ["map"] = 38},
	{["byte"] = 0x3B, ["bit"] = 4, ["name"] = "Aztec: Diddy Blueprint", ["type"] = "Blueprint", ["map"] = 38},
	{["byte"] = 0x3B, ["bit"] = 5, ["name"] = "Aztec: Lanky Blueprint", ["type"] = "Blueprint", ["map"] = 20},
	{["byte"] = 0x3B, ["bit"] = 6, ["name"] = "Aztec: Tiny Blueprint", ["type"] = "Blueprint", ["map"] = 38},
	{["byte"] = 0x3B, ["bit"] = 7, ["name"] = "Aztec: Chunky Blueprint", ["type"] = "Blueprint", ["map"] = 24},

	{["byte"] = 0x3C, ["bit"] = 0, ["name"] = "Factory: DK Blueprint", ["type"] = "Blueprint", ["map"] = 26},
	{["byte"] = 0x3C, ["bit"] = 1, ["name"] = "Factory: Diddy Blueprint", ["type"] = "Blueprint", ["map"] = 26},
	{["byte"] = 0x3C, ["bit"] = 2, ["name"] = "Factory: Lanky Blueprint", ["type"] = "Blueprint", ["map"] = 26},
	{["byte"] = 0x3C, ["bit"] = 3, ["name"] = "Factory: Tiny Blueprint", ["type"] = "Blueprint", ["map"] = 26},
	{["byte"] = 0x3C, ["bit"] = 4, ["name"] = "Factory: Chunky Blueprint", ["type"] = "Blueprint", ["map"] = 26},
	{["byte"] = 0x3C, ["bit"] = 5, ["name"] = "Galleon: DK Blueprint", ["type"] = "Blueprint", ["map"] = 30},
	{["byte"] = 0x3C, ["bit"] = 6, ["name"] = "Galleon: Diddy Blueprint", ["type"] = "Blueprint", ["map"] = 30},
	{["byte"] = 0x3C, ["bit"] = 7, ["name"] = "Galleon: Lanky Blueprint", ["type"] = "Blueprint", ["map"] = 30},

	{["byte"] = 0x3D, ["bit"] = 0, ["name"] = "Galleon: Tiny Blueprint", ["type"] = "Blueprint", ["map"] = 30},
	{["byte"] = 0x3D, ["bit"] = 1, ["name"] = "Galleon: Chunky Blueprint", ["type"] = "Blueprint", ["map"] = 30},
	{["byte"] = 0x3D, ["bit"] = 2, ["name"] = "Fungi: DK Blueprint", ["type"] = "Blueprint", ["map"] = 48},
	{["byte"] = 0x3D, ["bit"] = 3, ["name"] = "Fungi: Diddy Blueprint", ["type"] = "Blueprint", ["map"] = 64},
	{["byte"] = 0x3D, ["bit"] = 4, ["name"] = "Fungi: Lanky Blueprint", ["type"] = "Blueprint", ["map"] = 48},
	{["byte"] = 0x3D, ["bit"] = 5, ["name"] = "Fungi: Tiny Blueprint", ["type"] = "Blueprint", ["map"] = 48},
	{["byte"] = 0x3D, ["bit"] = 6, ["name"] = "Fungi: Chunky Blueprint", ["type"] = "Blueprint", ["map"] = 48},
	{["byte"] = 0x3D, ["bit"] = 7, ["name"] = "Caves: DK Blueprint", ["type"] = "Blueprint", ["map"] = 72},

	{["byte"] = 0x3E, ["bit"] = 0, ["name"] = "Caves: Diddy Blueprint", ["type"] = "Blueprint", ["map"] = 72},
	{["byte"] = 0x3E, ["bit"] = 1, ["name"] = "Caves: Lanky Blueprint", ["type"] = "Blueprint", ["map"] = 72},
	{["byte"] = 0x3E, ["bit"] = 2, ["name"] = "Caves: Tiny Blueprint", ["type"] = "Blueprint", ["map"] = 72},
	{["byte"] = 0x3E, ["bit"] = 3, ["name"] = "Caves: Chunky Blueprint", ["type"] = "Blueprint", ["map"] = 72},
	{["byte"] = 0x3E, ["bit"] = 4, ["name"] = "Castle: DK Blueprint", ["type"] = "Blueprint", ["map"] = 164},
	{["byte"] = 0x3E, ["bit"] = 5, ["name"] = "Castle: Diddy Blueprint", ["type"] = "Blueprint", ["map"] = 183},
	{["byte"] = 0x3E, ["bit"] = 6, ["name"] = "Castle: Lanky Blueprint", ["type"] = "Blueprint", ["map"] = 87},
	{["byte"] = 0x3E, ["bit"] = 7, ["name"] = "Castle: Tiny Blueprint", ["type"] = "Blueprint", ["map"] = 87},

	{["byte"] = 0x3F, ["bit"] = 0, ["name"] = "Castle: Chunky Blueprint", ["type"] = "Blueprint", ["map"] = 151},
	{["byte"] = 0x3F, ["bit"] = 1, ["name"] = "Isles: DK Blueprint", ["type"] = "Blueprint", ["map"] = 170},
	{["byte"] = 0x3F, ["bit"] = 2, ["name"] = "Isles: Diddy Blueprint", ["type"] = "Blueprint", ["map"] = 193},
	{["byte"] = 0x3F, ["bit"] = 3, ["name"] = "Isles: Lanky Blueprint", ["type"] = "Blueprint", ["map"] = 194},
	{["byte"] = 0x3F, ["bit"] = 4, ["name"] = "Isles: Tiny Blueprint", ["type"] = "Blueprint", ["map"] = 175},
	{["byte"] = 0x3F, ["bit"] = 5, ["name"] = "Isles: Chunky Blueprint", ["type"] = "Blueprint", ["map"] = 174},
	{["byte"] = 0x3F, ["bit"] = 6, ["name"] = "Snide's: DK BP Turned (Japes)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x3F, ["bit"] = 7, ["name"] = "Snide's: Diddy BP Turned (Japes)", ["type"] = "GB", ["map"] = 15},

	{["byte"] = 0x40, ["bit"] = 0, ["name"] = "Snide's: Lanky BP Turned (Japes)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x40, ["bit"] = 1, ["name"] = "Snide's: Tiny BP Turned (Japes)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x40, ["bit"] = 2, ["name"] = "Snide's: Chunky BP Turned (Japes)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x40, ["bit"] = 3, ["name"] = "Snide's: DK BP Turned (Aztec)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x40, ["bit"] = 4, ["name"] = "Snide's: Diddy BP Turned (Aztec)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x40, ["bit"] = 5, ["name"] = "Snide's: Lanky BP Turned (Aztec)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x40, ["bit"] = 6, ["name"] = "Snide's: Tiny BP Turned (Aztec)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x40, ["bit"] = 7, ["name"] = "Snide's: Chunky BP Turned (Aztec)", ["type"] = "GB", ["map"] = 15},

	{["byte"] = 0x41, ["bit"] = 0, ["name"] = "Snide's: DK BP Turned (Factory)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x41, ["bit"] = 1, ["name"] = "Snide's: Diddy BP Turned (Factory)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x41, ["bit"] = 2, ["name"] = "Snide's: Lanky BP Turned (Factory)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x41, ["bit"] = 3, ["name"] = "Snide's: Tiny BP Turned (Factory)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x41, ["bit"] = 4, ["name"] = "Snide's: Chunky BP Turned (Factory)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x41, ["bit"] = 5, ["name"] = "Snide's: DK BP Turned (Galleon)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x41, ["bit"] = 6, ["name"] = "Snide's: Diddy BP Turned (Galleon)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x41, ["bit"] = 7, ["name"] = "Snide's: Lanky BP Turned (Galleon)", ["type"] = "GB", ["map"] = 15},

	{["byte"] = 0x42, ["bit"] = 0, ["name"] = "Snide's: Tiny BP Turned (Galleon)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x42, ["bit"] = 1, ["name"] = "Snide's: Chunky BP Turned (Galleon)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x42, ["bit"] = 2, ["name"] = "Snide's: DK BP Turned (Fungi)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x42, ["bit"] = 3, ["name"] = "Snide's: Diddy BP Turned (Fungi)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x42, ["bit"] = 4, ["name"] = "Snide's: Lanky BP Turned (Fungi)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x42, ["bit"] = 5, ["name"] = "Snide's: Tiny BP Turned (Fungi)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x42, ["bit"] = 6, ["name"] = "Snide's: Chunky BP Turned (Fungi)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x42, ["bit"] = 7, ["name"] = "Snide's: DK BP Turned (Caves)", ["type"] = "GB", ["map"] = 15},

	{["byte"] = 0x43, ["bit"] = 0, ["name"] = "Snide's: Diddy BP Turned (Caves)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x43, ["bit"] = 1, ["name"] = "Snide's: Lanky BP Turned (Caves)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x43, ["bit"] = 2, ["name"] = "Snide's: Tiny BP Turned (Caves)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x43, ["bit"] = 3, ["name"] = "Snide's: Chunky BP Turned (Caves)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x43, ["bit"] = 4, ["name"] = "Snide's: DK BP Turned (Castle)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x43, ["bit"] = 5, ["name"] = "Snide's: Diddy BP Turned (Castle)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x43, ["bit"] = 6, ["name"] = "Snide's: Lanky BP Turned (Castle)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x43, ["bit"] = 7, ["name"] = "Snide's: Tiny BP Turned (Castle)", ["type"] = "GB", ["map"] = 15},

	{["byte"] = 0x44, ["bit"] = 0, ["name"] = "Snide's: Chunky BP Turned (Castle)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x44, ["bit"] = 1, ["name"] = "Snide's: DK BP Turned (Isles)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x44, ["bit"] = 2, ["name"] = "Snide's: Diddy BP Turned (Isles)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x44, ["bit"] = 3, ["name"] = "Snide's: Lanky BP Turned (Isles)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x44, ["bit"] = 4, ["name"] = "Snide's: Tiny BP Turned (Isles)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x44, ["bit"] = 5, ["name"] = "Snide's: Chunky BP Turned (Isles)", ["type"] = "GB", ["map"] = 15},
	{["byte"] = 0x44, ["bit"] = 6, ["name"] = "Japes: DK Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x44, ["bit"] = 7, ["name"] = "Japes: Diddy Banana Medal", ["type"] = "Medal"},

	{["byte"] = 0x45, ["bit"] = 0, ["name"] = "Japes: Lanky Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x45, ["bit"] = 1, ["name"] = "Japes: Tiny Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x45, ["bit"] = 2, ["name"] = "Japes: Chunky Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x45, ["bit"] = 3, ["name"] = "Aztec: DK Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x45, ["bit"] = 4, ["name"] = "Aztec: Diddy Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x45, ["bit"] = 5, ["name"] = "Aztec: Lanky Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x45, ["bit"] = 6, ["name"] = "Aztec: Tiny Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x45, ["bit"] = 7, ["name"] = "Aztec: Chunky Banana Medal", ["type"] = "Medal"},

	{["byte"] = 0x46, ["bit"] = 0, ["name"] = "Factory: DK Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x46, ["bit"] = 1, ["name"] = "Factory: Diddy Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x46, ["bit"] = 2, ["name"] = "Factory: Lanky Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x46, ["bit"] = 3, ["name"] = "Factory: Tiny Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x46, ["bit"] = 4, ["name"] = "Factory: Chunky Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x46, ["bit"] = 5, ["name"] = "Galleon: DK Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x46, ["bit"] = 6, ["name"] = "Galleon: Diddy Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x46, ["bit"] = 7, ["name"] = "Galleon: Lanky Banana Medal", ["type"] = "Medal"},

	{["byte"] = 0x47, ["bit"] = 0, ["name"] = "Galleon: Tiny Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x47, ["bit"] = 1, ["name"] = "Galleon: Chunky Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x47, ["bit"] = 2, ["name"] = "Fungi: DK Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x47, ["bit"] = 3, ["name"] = "Fungi: Diddy Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x47, ["bit"] = 4, ["name"] = "Fungi: Lanky Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x47, ["bit"] = 5, ["name"] = "Fungi: Tiny Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x47, ["bit"] = 6, ["name"] = "Fungi: Chunky Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x47, ["bit"] = 7, ["name"] = "Caves: DK Banana Medal", ["type"] = "Medal"},
	
	{["byte"] = 0x48, ["bit"] = 0, ["name"] = "Caves: Diddy Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x48, ["bit"] = 1, ["name"] = "Caves: Lanky Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x48, ["bit"] = 2, ["name"] = "Caves: Tiny Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x48, ["bit"] = 3, ["name"] = "Caves: Chunky Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x48, ["bit"] = 4, ["name"] = "Castle: DK Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x48, ["bit"] = 5, ["name"] = "Castle: Diddy Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x48, ["bit"] = 6, ["name"] = "Castle: Lanky Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x48, ["bit"] = 7, ["name"] = "Castle: Tiny Banana Medal", ["type"] = "Medal"},

	{["byte"] = 0x49, ["bit"] = 0, ["name"] = "Castle: Chunky Banana Medal", ["type"] = "Medal"},
	{["byte"] = 0x49, ["bit"] = 1, ["name"] = "Helm: DK Banana Medal", ["type"] = "Medal", ["map"] = 17},
	{["byte"] = 0x49, ["bit"] = 2, ["name"] = "Helm: Diddy Banana Medal", ["type"] = "Medal", ["map"] = 17},
	{["byte"] = 0x49, ["bit"] = 3, ["name"] = "Helm: Lanky Banana Medal", ["type"] = "Medal", ["map"] = 17},
	{["byte"] = 0x49, ["bit"] = 4, ["name"] = "Helm: Tiny Banana Medal", ["type"] = "Medal", ["map"] = 17},
	{["byte"] = 0x49, ["bit"] = 5, ["name"] = "Helm: Chunky Banana Medal", ["type"] = "Medal", ["map"] = 17},
	{["byte"] = 0x49, ["bit"] = 6, ["name"] = "Japes: Fairy (Water room)", ["type"] = "Fairy", ["map"] = 7},
	{["byte"] = 0x49, ["bit"] = 7, ["name"] = "Japes: Fairy (Painting room)", ["type"] = "Fairy", ["map"] = 13},

	{["byte"] = 0x4A, ["bit"] = 0, ["name"] = "Factory: Fairy (Funky)", ["type"] = "Fairy", ["map"] = 26},
	{["byte"] = 0x4A, ["bit"] = 1, ["name"] = "Galleon: Fairy (Chunky's chest room)", ["type"] = "Fairy", ["map"] = 30},
	{["byte"] = 0x4A, ["bit"] = 2, ["name"] = "Isles: Fairy (Factory Lobby)", ["type"] = "Fairy", ["map"] = 175},
	{["byte"] = 0x4A, ["bit"] = 3, ["name"] = "Isles: Fairy (Fungi Lobby)", ["type"] = "Fairy", ["map"] = 178},
	{["byte"] = 0x4A, ["bit"] = 4, ["name"] = "Fungi: Fairy (Diddy's Barn)", ["type"] = "Fairy", ["map"] = 56},
	{["byte"] = 0x4A, ["bit"] = 5, ["name"] = "Fungi: Fairy (DK's Barn)", ["type"] = "Fairy", ["map"] = 59},
	{["byte"] = 0x4A, ["bit"] = 6, ["name"] = "Caves: Fairy (Tiny 5DI)", ["type"] = "Fairy", ["map"] = 84},
	{["byte"] = 0x4A, ["bit"] = 7, ["name"] = "Helm: Fairy (1)", ["type"] = "Fairy", ["map"] = 17},

	{["byte"] = 0x4B, ["bit"] = 0, ["name"] = "Helm: Fairy (2)", ["type"] = "Fairy", ["map"] = 17},
	{["byte"] = 0x4B, ["bit"] = 1, ["name"] = "Aztec: Fairy (Llama Temple)", ["type"] = "Fairy", ["map"] = 20},
	{["byte"] = 0x4B, ["bit"] = 2, ["name"] = "Aztec: Fairy (Tiny 5DT)", ["type"] = "Fairy", ["map"] = 22},
	{["byte"] = 0x4B, ["bit"] = 3, ["name"] = "Factory: Fairy (Number Game area)", ["type"] = "Fairy", ["map"] = 26},
	{["byte"] = 0x4B, ["bit"] = 4, ["name"] = "Galleon: Fairy (Tiny 5DS)", ["type"] = "Fairy", ["map"] = 46},
	{["byte"] = 0x4B, ["bit"] = 5, ["name"] = "Castle: Fairy (Museum)", ["type"] = "Fairy", ["map"] = 113},
	{["byte"] = 0x4B, ["bit"] = 6, ["name"] = "Castle: Fairy (Tree)", ["type"] = "Fairy", ["map"] = 164},
	{["byte"] = 0x4B, ["bit"] = 7, ["name"] = "Isles: Fairy (Tree)", ["type"] = "Fairy", ["map"] = 34},

	{["byte"] = 0x4C, ["bit"] = 0, ["name"] = "Isles: Fairy (High)", ["type"] = "Fairy", ["map"] = 34},
	{["byte"] = 0x4C, ["bit"] = 1, ["name"] = "Caves: Fairy (Diddy Cabin)", ["type"] = "Fairy", ["map"] = 200},
	{["byte"] = 0x4C, ["bit"] = 2, ["name"] = "Japes: Crown", ["type"] = "Crown", ["map"] = 53},
	{["byte"] = 0x4C, ["bit"] = 3, ["name"] = "Aztec: Crown", ["type"] = "Crown", ["map"] = 73},
	{["byte"] = 0x4C, ["bit"] = 4, ["name"] = "Factory: Crown", ["type"] = "Crown", ["map"] = 155},
	{["byte"] = 0x4C, ["bit"] = 5, ["name"] = "Galleon: Crown", ["type"] = "Crown", ["map"] = 156},
	{["byte"] = 0x4C, ["bit"] = 6, ["name"] = "Fungi: Crown", ["type"] = "Crown", ["map"] = 159},
	{["byte"] = 0x4C, ["bit"] = 7, ["name"] = "Isles: Crown (Fungi Lobby)", ["type"] = "Crown", ["map"] = 157},

	{["byte"] = 0x4D, ["bit"] = 0, ["name"] = "Isles: Crown (Snide's)", ["type"] = "Crown", ["map"] = 158},
	{["byte"] = 0x4D, ["bit"] = 1, ["name"] = "Caves: Crown", ["type"] = "Crown", ["map"] = 160},
	{["byte"] = 0x4D, ["bit"] = 2, ["name"] = "Castle: Crown", ["type"] = "Crown", ["map"] = 161},
	{["byte"] = 0x4D, ["bit"] = 3, ["name"] = "Helm: Crown", ["type"] = "Crown", ["map"] = 162},
};

return flag_array;