defaultPreferences = {
	balloon_fight = {
	},
	bk = {
		position=true,
		positionStats=true,
		positionStatsMore=false,
		speed=true,
		angle=true,
		movement=true,
		floorProperties=true,
		wallProperties=true,
		ffunAnswer=false,
		ffunPattern=true,
		objectDespawn=true,
	},
	bt = {
		mapData = true,
		player = false,
		position = true,
		positionStats = true,
		positionStatsMore = false,
		speed = true,
		angle = true,
		movement = true,
		animation = false,
		camera = false,
		floorProperties = true,
		character = true,
	},
	cbfd = {
		position=true,
		positionStats=true,
		positionStatsMore=true,
		speed=true,
		angle=true,
		angleMore=false,
	},
	crash1 = {
		position=true,
		positionStats=true,
		positionStatsMore=false,
		speed=true,
		angle=true,
		player=true,
		mapData=true,
		boxData=true,
		progress=true,
		jumps=true,
	},
	crash2 = {
		position=true,
		positionStats=true,
		positionStatsMore=false,
		speed=true,
		angle=true,
		player=true,
		mapData=false,
		boxData=true,
		progress=true,
		progressMore=true,
		jumps=true,
	},
	crash3 = {
		position=true,
		positionStats=true,
		positionStatsMore=false,
		speed=true,
		angle=true,
		player=true,
		mapData=false,
		boxData=true,
		progress=true,
		progressMore=true,
		jumps=true,
	},
	dk64 = {
		mapData=true,
		cutsceneData=true,
		player=true,
		gamemode=true,
		fileView=true,
		flags=false,
		position=true,
		lag=false,
		positionStats=true,
		positionStatsMore=false,
		speed=true,
		angle=true,
		movement=true,
		animation=false,
		camera=false,
		noclip=true,
		bonearray=true,
		memory=false,
	},
	dkr = {
		position=true,
		positionStats=true,
		carProperties=true,
		speed=true,
		speedMore=false,
		angle=true,
		movingAngle=false,
		settings=true,
		player=true,
		mapData=true,
	},
	ej3d = {
		mapData=true,
		position=true,
		positionStats=true,
		positionStatsMore=true,
		angle=true,
		angleMore=false,
		animation=true,
		movement=true,
		marbleCount=true,
	},
	elmo = {
	},
	galahad = {
		screenPosition=true,
		speed=true,
		charge=true,
	},
	GBA_DrillDozer = {
		movement=true,
		drill=true,
		position=true,
		positionStats=true,
		positionStatsMore=true,
		speed=true,
	},
	GBA_Ty2 = {
		state=true,
		boomerang=true,
		superjump=true,
		position=true,
		positionStats=true,
		positionStatsMore=true,
		speed=true,
	},
	golden_axe_warrior = {
	},
	golvellius = {
		mapData=true,
		holeContents=true,
	},
	gran_turismo_2 = {
		general=true,
		position=true,
		positionStats=true,
	},
	impossible_mission = {
		mapData=true,
		igt=true,
		snoozeTimer=true,
		position=true,
		positionStats=true,
		distribution=true,
		flips=true,
		color=true,
		search=true,
	},
	lots = {
		mapData=true,
		continues=true,
		health=true,
		movement=true,
		position=true,
		positionStats=true,
		speed=true,
	},
	mercs_sms = {
		lag=true,
		gun=true,
		time=true,
		health=true,
		position=true,
		positionStats=true,
	},
	metroid = {
		screenPosition=true,
		position=true,
		positionStats=true,
		speed=true,
		frameRule=true,
		doorTimer=true,
	},
	miracle_world = {
		mapData=true,
		position=true,
		positionStats=true,
		speed=true,
	},
	mm = {
	},
	oot = {
	},
	penguin_land = {
		round=true,
		lives=true,
		igt=true,
		mapData=true,
		position=true,
		positionStats=true,
		speed=true,
		egg=true,
	},
	psycho_fox = {
		round=true,
		lives=true,
		position=true,
		positionStats=true,
		speed=true,
		screenPosition=true,
	},
	rats = {
		IGT=true,
		position=true,
		positionStats=true,
		positionStatsMore=false,
		speed=true,
	},
	rayman_2 = {
	},
	rush_2049 = {
		position=true,
		positionStats=true,
		positionStatsMore=true,
		speed=true,
	},
	shinobi_world = {
		position=true,
		positionStats=true,
		speed=true,
	},
	sm64 = {
		position=true,
		positionStats=true,
		positionStatsMore=true,
		speed=true,
		angle=true,
		angleMore=false,
	},
	smash64 = {
		player=true,
		movement=true,
		position=true,
		positionStats=true,
		speed=true,
		angle=true,
		shield=true,
		boomerang=true,
	},
	sonic1_sms = {
		mapData=true,
		igt=true,
		lives=true,
		rings=true,
		screenPosition=true,
		position=true,
		positionStats=true,
		speed=true,
	},
	sssv = {
		animal=true,
		position=true,
		positionStats=true,
		positionStatsMore=true,
		speed=true,
		angle=true,
		angleMore=false,
	},
	taz = {
		position=true,
		positionStats=true,
		speed=true,
		pmeter=true,
		jumps=true,
		mapData=true,
		igt=true,
	},
	tftt = {
		position=true,
		positionStats=true,
		ticker=true,
		rng=true,
		opponents=true,
		popAvailable=false,
		popAllocated=true,
		suspendedMen=true,
	},
	the_ninja = {
		position=true,
		positionStats=true,
		mapData=true,
		projectiles=true,
		hits=true,
		objects=true,
		enemies=true,
		boss=true,
	},
	ts2 = {
		position=true,
		positionStats=true,
		positionStatsMore=true,
		angle=true,
		angleMore=false,
	},
	wonder_boy_iii = {
		general=true,
		position=true,
		speed=true,
		positionStats=true,
	},
	wonder_boy_sms = {
		general=true,
		position=true,
		positionStats=true,
		speed=true,
	},
	wonder_boy_monster_world = {
		mapData=true,
		health=true,
		position=true,
		positionStats=true,
		speed=true,
	},
};