defaultPreferences = {
	balloon_fight = {

	},
	bk = {
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", true},
		{"speed", true},
		{"angle", true},
		{"movement", true},
		{"floorProperties", true},
		{"wallProperties", true},
		{"ffunAnswer", false},
		{"ffunPattern", true},
		{"objectDespawn", true},
	},
	bt = {
		{"mapData", true},
		{"player", false},
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", false},
		{"speed", true},
		{"angle", true},
		{"movement", true},
		{"animation", false},
		{"camera", false},
		{"floorProperties", true},
		{"character", true},
	},
	cbfd = {
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", true},
		{"speed", true},
		{"angle", true},
		{"angleMore", false},
	},
	crash1 = {
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", false},
		{"speed", true},
		{"angle", true},
		{"player", true},
		{"mapData", true},
		{"boxData", true},
		{"progress", true},
		{"jumps", true},
	},
	crash2 = {
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", false},
		{"speed", true},
		{"angle", true},
		{"player", true},
		{"mapData", false},
		{"boxData", true},
		{"progress", true},
		{"progressMore", true},
		{"jumps", true},
	},
	crash3 = {
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", false},
		{"speed", true},
		{"angle", true},
		{"player", true},
		{"mapData", false},
		{"boxData", true},
		{"progress", true},
		{"progressMore", true},
		{"jumps", true},
	},
	dk64 = {
		{"mapData", true},
		{"cutsceneData", true},
		{"player", true},
		{"gamemode", true},
		{"fileView", true},
		{"flags", false},
		{"position", true},
		{"lag", false},
		{"positionStats", true},
		{"positionStatsMore", false},
		{"speed", true},
		{"angle", true},
		{"movement", true},
		{"animation", false},
		{"camera", false},
		{"noclip", true},
		{"bonearray", true},
		{"memory", false},
	},
	dkr = {
		{"position", true},
		{"positionStats", true},
		{"carProperties", true},
		{"speed", true},
		{"speedMore", false},
		{"angle", true},
		{"movingAngle", false},
		{"settings", true},
		{"player", true},
		{"mapData", true},
	},
	ej3d = {
		{"mapData", true},
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", true},
		{"angle", true},
		{"angleMore", false},
		{"animation", true},
		{"movement", true},
	},
	elmo = {
	},
	galahad = {
		{"screenPosition", true},
		{"speed", true},
		{"charge", true},
	},
	GBA_DrillDozer = {
		{"movement", true},
		{"drill", true},
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", true},
		{"speed", true},
	},
	GBA_Ty2 = {
		{"state", true},
		{"boomerang", true},
		{"superjump", true},
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", true},
		{"speed", true},
	},
	golden_axe_warrior = {
	},
	golvellius = {
		{"mapData", true},
		{"holeContents", true},
	},
	gran_turismo_2 = {
		{"car", true},
		{"mapData", true},
		{"cash", true},
		{"position", true},
		{"positionStats", true},
	},
	impossible_mission = {
		{"mapData", true},
		{"igt", true},
		{"snoozeTimer", true},
		{"position", true},
		{"positionStats", true},
		{"distribution", true},
		{"flips", true},
		{"color", true},
		{"search", true},
	},
	lots = {
		{"mapData", true},
		{"continues", true},
		{"health", true},
		{"movement", true},
		{"position", true},
		{"positionStats", true},
		{"speed", true},
	},
	mercs_sms = {
		{"lag", true},
		{"gun", true},
		{"time", true},
		{"health", true},
		{"position", true},
		{"positionStats", true},
	},
	metroid = {
		{"screenPosition", true},
		{"position", true},
		{"positionStats", true},
		{"speed", true},
		{"frameRule", true},
		{"doorTimer", true},
	},
	miracle_world = {
		{"mapData", true},
		{"position", true},
		{"positionStats", true},
		{"speed", true},
	},
	mm = {
	},
	oot = {
	},
	penguin_land = {
		{"round", true},
		{"lives", true},
		{"igt", true},
		{"mapData", true},
		{"position", true},
		{"positionStats", true},
		{"speed", true},
		{"egg", true},
	},
	psycho_fox = {
		{"round", true},
		{"lives", true},
		{"position", true},
		{"positionStats", true},
		{"speed", true},
		{"screenPosition", true},
	},
	rats = {
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", true},
		{"speed", true},
	},
	rayman_2 = {
	},
	rush_2049 = {
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", true},
		{"speed", true},
	},
	shinobi_world = {
		{"position", true},
		{"positionStats", true},
		{"speed", true},
	},
	sm64 = {
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", true},
		{"speed", true},
		{"angle", true},
		{"angleMore", false},
	},
	smash64 = {
		{"player", true},
		{"movement", true},
		{"position", true},
		{"positionStats", true},
		{"speed", true},
		{"angle", true},
		{"shield", true},
		{"boomerang", true},
	},
	sonic1_sms = {
		{"mapData", true},
		{"igt", true},
		{"lives", true},
		{"rings", true},
		{"screenPosition", true},
		{"position", true},
		{"positionStats", true},
		{"speed", true},
	},
	sssv = {
		{"animal", true},
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", true},
		{"speed", true},
		{"angle", true},
		{"angleMore", false},
	},
	taz = {
		{"position", true},
		{"positionStats", true},
		{"speed", true},
		{"pmeter", true},
		{"jumps", true},
		{"mapData", true},
		{"igt", true},
	},
	tftt = {
		{"position", true},
		{"positionStats", true},
		{"ticker", true},
		{"rng", true},
		{"opponents", true},
		{"popAvailable", false},
		{"popAllocated", true},
		{"suspendedMen", true},
	},
	the_ninja = {
		{"position", true},
		{"positionStats", true},
		{"mapData", true},
		{"projectiles", true},
		{"hits", true},
		{"objects", true},
		{"enemies", true},
		{"boss", true},
	},
	ts2 = {
		{"position", true},
		{"positionStats", true},
		{"positionStatsMore", true},
		{"angle", true},
		{"angleMore", false},
	},
	wonder_boy_monster_world = {
		{"mapData", true},
		{"health", true},
		{"position", true},
		{"positionStats", true},
		{"speed", true},
	},
};
userPreferences = {
	balloon_fight = {
	},
	bk = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"movement", nil},
		{"floorProperties", nil},
		{"wallProperties", nil},
		{"ffunAnswer", nil},
		{"ffunPattern", nil},
		{"objectDespawn", nil},
	},
	bt = {
		{"mapData", nil},
		{"player", nil},
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"movement", nil},
		{"animation", nil},
		{"camera", nil},
		{"floorProperties", nil},
		{"character", nil},
	},
	cbfd = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"angleMore", nil},
	},
	crash1 = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"player", nil},
		{"mapData", nil},
		{"boxData", nil},
		{"progress", nil},
		{"jumps", nil},
	},
	crash2 = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"player", nil},
		{"mapData", nil},
		{"boxData", nil},
		{"progress", nil},
		{"progressMore", nil},
		{"jumps", nil},
	},
	crash3 = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"player", nil},
		{"mapData", nil},
		{"boxData", nil},
		{"progress", nil},
		{"progressMore", nil},
		{"jumps", nil},
	},
	dk64 = {
		{"mapData", nil},
		{"cutsceneData", nil},
		{"player", nil},
		{"gamemode", nil},
		{"fileView", nil},
		{"flags", nil},
		{"position", nil},
		{"lag", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"movement", nil},
		{"animation", nil},
		{"camera", nil},
		{"noclip", nil},
		{"bonearray", nil},
		{"memory", nil},
	},
	dkr = {
		{"position", nil},
		{"positionStats", nil},
		{"carProperties", nil},
		{"speed", nil},
		{"speedMore", nil},
		{"angle", nil},
		{"movingAngle", nil},
		{"settings", nil},
		{"player", nil},
		{"mapData", nil},
	},
	ej3d = {
		{"mapData", nil},
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"angle", nil},
		{"angleMore", nil},
		{"animation", nil},
		{"movement", nil},
	},
	elmo = {
	},
	galahad = {
		{"screenPosition", nil},
		{"speed", nil},
		{"charge", nil},
	},
	GBA_DrillDozer = {
		{"movement", nil},
		{"drill", nil},
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
	},
	GBA_Ty2 = {
		{"state", nil},
		{"boomerang", nil},
		{"superjump", nil},
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
	},
	golden_axe_warrior = {
	},
	golvellius = {
		{"mapData", nil},
		{"holeContents", nil},
	},
	gran_turismo_2 = {
		{"car", nil},
		{"mapData", nil},
		{"cash", nil},
		{"position", nil},
		{"positionStats", nil},
	},
	impossible_mission = {
		{"mapData", nil},
		{"igt", nil},
		{"snoozeTimer", nil},
		{"position", nil},
		{"positionStats", nil},
		{"distribution", nil},
		{"flips", nil},
		{"color", nil},
		{"search", nil},
	},
	lots = {
		{"mapData", nil},
		{"continues", nil},
		{"health", nil},
		{"movement", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
	},
	mercs_sms = {
		{"lag", nil},
		{"gun", nil},
		{"time", nil},
		{"health", nil},
		{"position", nil},
		{"positionStats", nil},
	},
	metroid = {
		{"screenPosition", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
		{"frameRule", nil},
		{"doorTimer", nil},
	},
	miracle_world = {
		{"mapData", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
	},
	mm = {
	},
	oot = {
	},
	penguin_land = {
		{"round", nil},
		{"lives", nil},
		{"igt", nil},
		{"mapData", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
		{"egg", nil},
	},
	psycho_fox = {
		{"round", nil},
		{"lives", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
		{"screenPosition", nil},
	},
	rats = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
	},
	rayman_2 = {
	},
	rush_2049 = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
	},
	shinobi_world = {
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
	},
	sm64 = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"angleMore", nil},
	},
	smash64 = {
		{"player", nil},
		{"movement", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
		{"angle", nil},
		{"shield", nil},
		{"boomerang", nil},
	},
	sonic1_sms = {
		{"mapData", nil},
		{"igt", nil},
		{"lives", nil},
		{"rings", nil},
		{"screenPosition", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
	},
	sssv = {
		{"animal", nil},
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"angleMore", nil},
	},
	taz = {
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
		{"pmeter", nil},
		{"jumps", nil},
		{"mapData", nil},
		{"igt", nil},
	},
	tftt = {
		{"position", nil},
		{"positionStats", nil},
		{"ticker", nil},
		{"rng", nil},
		{"opponents", nil},
		{"popAvailable", nil},
		{"popAllocated", nil},
		{"suspendedMen", nil},
	},
	the_ninja = {
		{"position", nil},
		{"positionStats", nil},
		{"mapData", nil},
		{"projectiles", nil},
		{"hits", nil},
		{"objects", nil},
		{"enemies", nil},
		{"boss", nil},
	},
	ts2 = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"angle", nil},
		{"angleMore", nil},
	},
	wonder_boy_monster_world = {
		{"mapData", nil},
		{"health", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
	},
};
currentPreferences = {
	balloon_fight = {
	},
	bk = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"movement", nil},
		{"floorProperties", nil},
		{"wallProperties", nil},
		{"ffunAnswer", nil},
		{"ffunPattern", nil},
		{"objectDespawn", nil},
	},
	bt = {
		{"mapData", nil},
		{"player", nil},
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"movement", nil},
		{"animation", nil},
		{"camera", nil},
		{"floorProperties", nil},
		{"character", nil},
	},
	cbfd = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"angleMore", nil},
	},
	crash1 = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"player", nil},
		{"mapData", nil},
		{"boxData", nil},
		{"progress", nil},
		{"jumps", nil},
	},
	crash2 = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"player", nil},
		{"mapData", nil},
		{"boxData", nil},
		{"progress", nil},
		{"progressMore", nil},
		{"jumps", nil},
	},
	crash3 = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"player", nil},
		{"mapData", nil},
		{"boxData", nil},
		{"progress", nil},
		{"progressMore", nil},
		{"jumps", nil},
	},
	dk64 = {
		{"mapData", nil},
		{"cutsceneData", nil},
		{"player", nil},
		{"gamemode", nil},
		{"fileView", nil},
		{"flags", nil},
		{"position", nil},
		{"lag", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"movement", nil},
		{"animation", nil},
		{"camera", nil},
		{"noclip", nil},
		{"bonearray", nil},
		{"memory", nil},
	},
	dkr = {
		{"position", nil},
		{"positionStats", nil},
		{"carProperties", nil},
		{"speed", nil},
		{"speedMore", nil},
		{"angle", nil},
		{"movingAngle", nil},
		{"settings", nil},
		{"player", nil},
		{"mapData", nil},
	},
	donald_land = {
		{"igt", nil},
		{"player", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
		{"bombTimer", nil},
	},
	ej3d = {
		{"mapData", nil},
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"angle", nil},
		{"angleMore", nil},
		{"animation", nil},
		{"movement", nil},
	},
	elmo = {
	},
	galahad = {
		{"screenPosition", nil},
		{"speed", nil},
		{"charge", nil},
	},
	GBA_DrillDozer = {
		{"movement", nil},
		{"drill", nil},
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
	},
	GBA_Ty2 = {
		{"state", nil},
		{"boomerang", nil},
		{"superjump", nil},
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
	},
	golden_axe_warrior = {
	},
	golvellius = {
		{"mapData", nil},
		{"holeContents", nil},
	},
	gran_turismo_2 = {
		{"car", nil},
		{"mapData", nil},
		{"cash", nil},
		{"position", nil},
		{"positionStats", nil},
	},
	impossible_mission = {
		{"mapData", nil},
		{"igt", nil},
		{"snoozeTimer", nil},
		{"position", nil},
		{"positionStats", nil},
		{"distribution", nil},
		{"flips", nil},
		{"color", nil},
		{"search", nil},
	},
	lots = {
		{"mapData", nil},
		{"continues", nil},
		{"health", nil},
		{"movement", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
	},
	mercs_sms = {
		{"lag", nil},
		{"gun", nil},
		{"time", nil},
		{"health", nil},
		{"position", nil},
		{"positionStats", nil},
	},
	metroid = {
		{"screenPosition", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
		{"frameRule", nil},
		{"doorTimer", nil},
	},
	miracle_world = {
		{"mapData", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
	},
	mm = {
	},
	oot = {
	},
	penguin_land = {
		{"round", nil},
		{"lives", nil},
		{"igt", nil},
		{"mapData", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
		{"egg", nil},
	},
	psycho_fox = {
		{"round", nil},
		{"lives", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
		{"screenPosition", nil},
	},
	rats = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
	},
	rayman_2 = {
	},
	rush_2049 = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
	},
	shinobi_world = {
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
	},
	sm64 = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"angleMore", nil},
	},
	smash64 = {
		{"player", nil},
		{"movement", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
		{"angle", nil},
		{"shield", nil},
		{"boomerang", nil},
	},
	sonic1_sms = {
		{"mapData", nil},
		{"igt", nil},
		{"lives", nil},
		{"rings", nil},
		{"screenPosition", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
	},
	sssv = {
		{"animal", nil},
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"speed", nil},
		{"angle", nil},
		{"angleMore", nil},
	},
	taz = {
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
		{"pmeter", nil},
		{"jumps", nil},
		{"mapData", nil},
		{"igt", nil},
	},
	tftt = {
		{"position", nil},
		{"positionStats", nil},
		{"ticker", nil},
		{"rng", nil},
		{"opponents", nil},
		{"popAvailable", nil},
		{"popAllocated", nil},
		{"suspendedMen", nil},
	},
	the_ninja = {
		{"position", nil},
		{"positionStats", nil},
		{"mapData", nil},
		{"projectiles", nil},
		{"hits", nil},
		{"objects", nil},
		{"enemies", nil},
		{"boss", nil},
	},
	ts2 = {
		{"position", nil},
		{"positionStats", nil},
		{"positionStatsMore", nil},
		{"angle", nil},
		{"angleMore", nil},
	},
	wonder_boy_monster_world = {
		{"mapData", nil},
		{"health", nil},
		{"position", nil},
		{"positionStats", nil},
		{"speed", nil},
	},
};