/*-------------------------------
| ENUMS
---------------------------------*/
//Items
[ItemIndex_Timer_Skull]: 0x01
[ItemIndex_Timer_Propellor]: 0x03
[ItemIndex_Timer_ChristmasTree]: 0x05
[ItemIndex_Timer_Hourglass]: 0x06
[ItemIndex_Notes]: 0x0C
[ItemIndex_Eggs]: 0x0D
[ItemIndex_Jiggies_CurrentLevel]: 0x12
[ItemIndex_RedFeather]: 0x0F
[ItemIndex_GoldFeather]: 0x10
[ItemIndex_Jinjos_CurrentLevel]: 0x12
[ItemIndex_EmptyHoneycombPiece]: 0x13
[ItemIndex_Health]: 0x14
[ItemIndex_HealthContainers]: 0x15
[ItemIndex_Lives]: 0x16
[ItemIndex_Air]: 0x17
[ItemIndex_GoldBullions]: 0x18
[ItemIndex_Orange]: 0x19
[ItemIndex_PlayerVileScore]: 0x1A
[ItemIndex_VileVileScore]: 0x1B
[ItemIndex_MumboTokens_OnHand]: 0x1C
[ItemIndex_Grumblie]: 0x1D
[ItemIndex_Yumblie]: 0x1E
[ItemIndex_GreenPresent]: 0x1F
[ItemIndex_BluePresent]: 0x20
[ItemIndex_RedPresent]: 0x21
[ItemIndex_Caterpillar]: 0x22
[ItemIndex_Acorn]: 0x23
[ItemIndex_Twinklie]: 0x24
[ItemIndex_MumboTokens]: 0x25
[ItemIndex_Jiggies]: 0x26
[ItemIndex_JokerCard]: 0x27


//Levels
[LevelIndex_MumbosMountain]: 0x01
[LevelIndex_TreasureTroveCove]: 0x02
[LevelIndex_ClankersCavern]: 0x03
[LevelIndex_BubblegloopSwamp]: 0x04
[LevelIndex_FreezeezyPeak]: 0x05
[LevelIndex_Lair]: 0x06
[LevelIndex_GobisValley]: 0x07
[LevelIndex_ClickClockWood]: 0x08
[LevelIndex_RustyBucketBay]: 0x09
[LevelIndex_MadMonsterMansion]: 0x0A
[LevelIndex_SpiralMountain]: 0x0B
[LevelIndex_FinalBattle]: 0x0C


//Maps
[MapIndex_SM_Main]: 0x01
[MapIndex_MM_Main]: 0x02

[MapIndex_TTC_BlubbersShip]: 0x05
[MapIndex_TTC_NippersShell]: 0x06
[MapIndex_TTC_TreasureTroveCove]: 0x07

[MapIndex_TTC_Sandcastle]: 0x0A
[MapIndex_CC_Main]: 0x0B
[MapIndex_MM_TickersTower]: 0x0C
[MapIndex_BGS_BubblegloopSwamp]: 0x0D
[MapIndex_MM_MumbosSkull]: 0x0E

[MapIndex_BGS_MrVile]: 0x10
[MapIndex_BGS_Tanktup]: 0x11
[MapIndex_GV_GobisValley]: 0x12
[MapIndex_GV_MatchingPuzzle]: 0x13
[MapIndex_GV_SandybuttsMaze]: 0x14
[MapIndex_GV_WaterPyramid]: 0x15
[MapIndex_GV_RubbesPyramid]: 0x16

[MapIndex_GV_Sphinx]: 0x1A
[MapIndex_MMM_Main]: 0x1B
[MapIndex_MMM_Church]: 0x1C
[MapIndex_MMM)Cellar]: 0x1D
[MapIndex_Intro_Nintendo]: 0x1E
[MapIndex_Intro_Rareware]: 0x1F
[MapIndex_End_Not100]: 0x20
[MapIndex_CC_SlowSawbladeRoom]: 0x21
[MapIndex_CC_RingRoom]: 0x22
[MapIndex_CC_FastSawbladeRoom]: 0x23
[MapIndex_MMM_TumblarShed]: 0x24
[MapIndex_MMM_Well]: 0x25
[MapIndex_MMM_DiningRoom]: 0x26
[MapIndex_FP_Main]: 0x27
[MapIndex_MMM_Room1]: 0x28
[MapIndex_MMM_Room2]: 0x29
[MapIndex_MMM_DiningRoom]: 0x2A
[MapIndex_MMM_Church2]: 0x2B
[MapIndex_MMM_Bathroom]: 0x2C
[MapIndex_MMM_Bedroom]: 0x2D

//

