/*-------------------------------
| ENUMS
---------------------------------*/
//Buttons
[ButtonIndex_Start]:    0x00
[ButtonIndex_Z]:        0x01
[ButtonIndex_L]:        0x02
[ButtonIndex_R]:        0x03
[ButtonIndex_D_Up]:     0x04
[ButtonIndex_D_Down]:   0x05
[ButtonIndex_D_Left]:   0x06
[ButtonIndex_D_Right]:  0x07
[ButtonIndex_A]:        0x08
[ButtonIndex_B]:        0x09
[ButtonIndex_D_Left]:   0x0A
[ButtonIndex_D_Down]:   0x0B
[ButtonIndex_D_Up]:     0x0C
[ButtonIndex_D_Right]:  0x0D

//Items
[ItemIndex_Timer_Skull]: 0x01
[ItemIndex_Timer_Propellor]: 0x03
[ItemIndex_Timer_ChristmasTree]: 0x05
[ItemIndex_Timer_Hourglass]: 0x06
[ItemIndex_Notes]: 0x0C
[ItemIndex_Eggs]: 0x0D
[ItemIndex_Jiggies_CurrentLevel]: 0x12
[ItemIndex_RedFeather]: 0x0F
[ItemIndex_GoldFeather]: 0x10
[ItemIndex_Jinjos_CurrentLevel]: 0x12
[ItemIndex_EmptyHoneycombPiece]: 0x13
[ItemIndex_Health]: 0x14
[ItemIndex_HealthContainers]: 0x15
[ItemIndex_Lives]: 0x16
[ItemIndex_Air]: 0x17
[ItemIndex_GoldBullions]: 0x18
[ItemIndex_Orange]: 0x19
[ItemIndex_PlayerVileScore]: 0x1A
[ItemIndex_VileVileScore]: 0x1B
[ItemIndex_MumboTokens_OnHand]: 0x1C
[ItemIndex_Grumblie]: 0x1D
[ItemIndex_Yumblie]: 0x1E
[ItemIndex_GreenPresent]: 0x1F
[ItemIndex_BluePresent]: 0x20
[ItemIndex_RedPresent]: 0x21
[ItemIndex_Caterpillar]: 0x22
[ItemIndex_Acorn]: 0x23
[ItemIndex_Twinklie]: 0x24
[ItemIndex_MumboTokens]: 0x25
[ItemIndex_Jiggies]: 0x26
[ItemIndex_JokerCard]: 0x27


//Levels
[LevelIndex_MumbosMountain]: 0x01
[LevelIndex_TreasureTroveCove]: 0x02
[LevelIndex_ClankersCavern]: 0x03
[LevelIndex_BubblegloopSwamp]: 0x04
[LevelIndex_FreezeezyPeak]: 0x05
[LevelIndex_Lair]: 0x06
[LevelIndex_GobisValley]: 0x07
[LevelIndex_ClickClockWood]: 0x08
[LevelIndex_RustyBucketBay]: 0x09
[LevelIndex_MadMonsterMansion]: 0x0A
[LevelIndex_SpiralMountain]: 0x0B
[LevelIndex_FinalBattle]: 0x0C


//Maps
[MapIndex_SM_Main]: 0x01
[MapIndex_MM_Main]: 0x02

[MapIndex_TTC_BlubbersShip]: 0x05
[MapIndex_TTC_NippersShell]: 0x06
[MapIndex_TTC_TreasureTroveCove]: 0x07

[MapIndex_TTC_Sandcastle]: 0x0A
[MapIndex_CC_Main]: 0x0B
[MapIndex_MM_TickersTower]: 0x0C
[MapIndex_BGS_BubblegloopSwamp]: 0x0D
[MapIndex_MM_MumbosSkull]: 0x0E

[MapIndex_BGS_MrVile]: 0x10
[MapIndex_BGS_Tanktup]: 0x11
[MapIndex_GV_GobisValley]: 0x12
[MapIndex_GV_MatchingPuzzle]: 0x13
[MapIndex_GV_SandybuttsMaze]: 0x14
[MapIndex_GV_WaterPyramid]: 0x15
[MapIndex_GV_RubbesPyramid]: 0x16

[MapIndex_GV_Sphinx]: 0x1A
[MapIndex_MMM_Main]: 0x1B
[MapIndex_MMM_Church]: 0x1C
[MapIndex_MMM_Cellar]: 0x1D
[MapIndex_Intro_Nintendo]: 0x1E
[MapIndex_Intro_Rareware]: 0x1F
[MapIndex_End_Not100]: 0x20
[MapIndex_CC_SlowSawbladeRoom]: 0x21
[MapIndex_CC_RingRoom]: 0x22
[MapIndex_CC_FastSawbladeRoom]: 0x23
[MapIndex_MMM_TumblarShed]: 0x24
[MapIndex_MMM_Well]: 0x25
[MapIndex_MMM_DiningRoom]: 0x26
[MapIndex_FP_Main]: 0x27
[MapIndex_MMM_Room1]: 0x28
[MapIndex_MMM_Room2]: 0x29
[MapIndex_MMM_DiningRoom]: 0x2A
[MapIndex_MMM_Church2]: 0x2B
[MapIndex_MMM_Bathroom]: 0x2C
[MapIndex_MMM_Bedroom]: 0x2D
[MapIndex_MMM_Room6Floorboards]: 0x2E
[MapIndex_MMM_RainBarrel]: 0x2F
[MapIndex_MMM_MumbosSkull]: 0x30
[MapIndex_RBB_Main]: 0x31

[MapIndex_RBB_EngineRoom]: 	0x34
[MapIndex_RBB_Warehouse1]: 	0x35
[MapIndex_RBB_Warehouse2]: 	0x36
[MapIndex_RBB_Container1]: 	0x37
[MapIndex_RBB_Container3]: 	0x38
[MapIndex_RBB_BunkRoom]: 	0x39
[MapIndex_RBB_BossBoomBox]:	0x3A
[MapIndex_RBB_StoreRoom]:	0x3B
[MapIndex_RBB_Kitchen]:		0x3C
[MapIndex_RBB_NavigationRoom]:	0x3D
[MapIndex_RBB_Container2]:	0x3E
[MapIndex_RBB_CaptainsCabin]:	0x3F
[MapIndex_CCW_SeasonHub]:	0x40
[MapIndex_FP_BoggysIgloo]:	0x41

[MapIndex_CCW_Spring]:	0x43
[MapIndex_CCW_Summer]:	0x44
[MapIndex_CCW_Autumn]:	0x45
[MapIndex_CCW_Winter]:	0x46
[MapIndex_BGS_MumbosSkull]:	0x47
[MapIndex_FP_MumbosSkull]:	0x48
[MapIndex_CCW_MumbosSkull_Spring]:	0x4A
[MapIndex_CCW_MumbosSkull_Summer]:	0x4B
[MapIndex_CCW_MumbosSkull_Autumn]:	0x4C
[MapIndex_CCW_MumbosSkull_Winter]:	0x4D

[MapIndex_FP_XmasTree]:	0x53

[MapIndex_CCW_Zubbas_Summer]:	0x5A
[MapIndex_CCW_Zubbas_Spring]:	0x5B
[MapIndex_CCW_Zubbas_Autumn]:	0x5C

[MapIndex_CCW_Nabnuts_Spring]:	0x5E
[MapIndex_CCW_Nabnuts_Summer]:	0x5F
[MapIndex_CCW_Nabnuts_Autumn]:	0x60
[MapIndex_CCW_Nabnuts_Winter]:	0x61
[MapIndex_CCW_Nabnuts_Room1_Winter]:	0x62
[MapIndex_CCW_Nabnuts_Room1_Autumn]:	0x63
[MapIndex_CCW_Nabnuts_Room2_Winter]:	0x64 
[MapIndex_CCW_TopRoom_Spring]:	0x65
[MapIndex_CCW_TopRoom_Summer]:	0x66
[MapIndex_CCW_TopRoom_Autumn]:	0x67
[MapIndex_CCW_TopRoom_Winter]:	0x68
[MapIndex_Lair_MMLobby]:	0x69
[MapIndex_Lair_TTCPuzzle]:	0x6A
[MapIndex_Lair_CCWPuzzle]:	0x6B
[MapIndex_Lair_RedCauldron]:	0x6C
[MapIndex_Lair_TTCLobby]:	0x6D
[MapIndex_Lair_GVLobby]:	0x6E
[MapIndex_Lair_FPLobby]:	0x6F
[MapIndex_Lair_CCLobby]:	0x70
[MapIndex_Lair_Statue]:	0x71
[MapIndex_Lair_BGSLobby]:	0x72

[MapIndex_Lair_GVLobby]:	0x74
[MapIndex_Lair_GVPuzzle]:	0x74
[MapIndex_Lair_MMMLobby]:	0x75
[MapIndex_Lair_640NoteDoorRoom]:	0x76
[MapIndex_Lair_RBBLobby]:	0x77
[MapIndex_Lair_RBBPuzzle]:	0x78
[MapIndex_Lair_CCWLobby]:	0x79
[MapIndex_Lair_Crypt]:	0x7A
[MapIndex_Intro_Lair1_Scene1]:	0x7B
[MapIndex_Intro_BanjosHouse1_Scenes_3_7]:	0x7C
[MapIndex_Intro_SpiralA_Scenes_2_4]:	0x7D
[MapIndex_Intro_SpiralB_Scenes_5_6]:	0x7E
[MapIndex_FP_WozzasCave]:	0x7F
[MapIndex_Lair_Floor3_AreaA4]:	0x80
[MapIndex_Intro_Lair2]:	0x81
[MapIndex_Intro_Lair3_Machine1]:	0x82
[MapIndex_Intro_Lair4_GameOver]:	0x83
[MapIndex_Intro_Lair5]:	0x84
[MapIndex_Intro_SpiralC]:	0x85
[MapIndex_Intro_SpiralD]:	0x86
[MapIndex_Intro_SpiralE]:	0x87
[MapIndex_Intro_spiralE]:	0x88
[MapIndex_Intro_SpiralF]:	0x89
[MapIndex_Intro_BanjosHouse2]:	0x8A
[MapIndex_Intro_BanjosHouse3]:	0x8B
[MapIndex_Lair_RBB_AnchorRoom]:	0x8C
[MapIndex_SM_BanjosHouse]:	0x8D
[MapIndex_MMM_Loggo]:	0x8E
[MapIndex_Lair_FurnaceFun]:	0x8F
[MapIndex_TTC_SharkfoodIsland]:	0x90
[MapIndex_Lair_Battlements]:	0x91
[MapIndex_FileSelectScreen]:	0x92
[MapIndex_GV_SecretChamber]:	0x93
[MapIndex_Lair_Dingpot]:	0x94
[MapIndex_Intro_SpiralG]:	0x95
[MapIndex_EndScene3_All100]:	0x96
[MapIndex_EndScene]:	0x97
[MapIndex_EndScene4]:	0x98
[MapIndex_Intro_GruntyThreat1]:	0x99
[MapIndex_Intro_GruntyThreat2]:	0x9A



//MOVEMENT STATES
[MovementState_Flight_Entering]: 0x23



//GAME PROGRESS FLAGS

[GameProgressFlag_CCWSpringOpen]: 0x8B
[GameProgressFlag_CCWSummerOpen]: 0x8C
[GameProgressFlag_CCWAutumnOpen]: 0x8D
[GameProgressFlag_CCWWinterOpen]: 0x8E